### ISSUE TITLE
An error happened when I training On macOS

### ISSUE THREAD

**Issue by nagaame** [Akegarasu/lora-scripts#10]
* OS version 13.2
* Python 3.10.9
* Device MacBook Pro M1 Pro 32G
Error info

```python

caching latents.
  0%|                                                                                                                         | 0/32 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/cpp/Downloads/sd/lora-scripts/./sd-scripts/train_network.py", line 548, in <module>
    train(args)
  File "/Users/cpp/Downloads/sd/lora-scripts/./sd-scripts/train_network.py", line 167, in train
    train_dataset.cache_latents(vae)
  File "/Users/cpp/Downloads/sd/lora-scripts/sd-scripts/library/train_util.py", line 508, in cache_latents
    info.latents = vae.encode(img_tensor).latent_dist.sample().squeeze(0).to("cpu")
  File "/Users/cpp/Downloads/sd/lora-scripts/venv/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 114, in encode
    h = self.encoder(x)
  File "/Users/cpp/Downloads/sd/lora-scripts/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/cpp/Downloads/sd/lora-scripts/venv/lib/python3.10/site-packages/diffusers/models/vae.py", line 101, in forward
    sample = self.conv_in(sample)
  File "/Users/cpp/Downloads/sd/lora-scripts/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/cpp/Downloads/sd/lora-scripts/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/cpp/Downloads/sd/lora-scripts/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
Traceback (most recent call last):
  File "/Users/cpp/Downloads/sd/lora-scripts/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/Users/cpp/Downloads/sd/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/Users/cpp/Downloads/sd/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/Users/cpp/Downloads/sd/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 552, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/Users/cpp/Downloads/sd/lora-scripts/venv/bin/python3', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=./sd-models/model.ckpt', '--train_data_dir=./train/nonomi', '--output_dir=./output', '--logging_dir=./logs', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=20', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--network_dim=64', '--network_alpha=32', '--output_name=nonomi', '--train_batch_size=3', '--save_every_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--xformers', '--shuffle_caption', '--use_8bit_adam']' returned non-zero exit status 1.


```

**Comment by Akegarasu** [comment]
change percision to fp32.

**Comment by FrenkYang0918** [comment]
> change precision to fp32.
I have the same problem.
How to change precision?

**Comment by FrenkYang0918** [comment]
我也有相同的错误（但在Colab上运行），请问如何调整精度为fp32

**Comment by Akegarasu** [comment]
Remove `--mixed_precision=fp16` in train script.
