### ISSUE TITLE
 CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by cityvoice** [Akegarasu/lora-scripts#101]
```
 poch 1/10
Error CUDA driver version is insufficient for CUDA runtime version at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Users\cityv\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cityv\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\webroot\lora-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\webroot\lora-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "E:\webroot\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
...
```

I'm using a integrated Intel GPU(iris xe graphics). os is win 11, torch==2.0.0+cu118 torchvision==0.15.1+cu118. I have no idea how to fix it, any ideas? thanks!

by the way, stable diffusion web ui runs ok in my pc.

**Comment by Akegarasu** [comment]
不支持使用cpu训练
