### ISSUE TITLE
无法开始训练（已确认venv是python 3.10.8）

### ISSUE THREAD

**Issue by farcloudy** [Akegarasu/lora-scripts#12]
subprocess.CalledProcessError: Command '['D:\\stable-diffusion-webui\\lora-scripts\\venv\\Scripts\\python.exe', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=D:/stable-diffusion-webui/models/Stable-diffusion/protogenX34Photorealism_1.ckpt', '--train_data_dir=./train/wq', '--output_dir=./output', '--logging_dir=./logs', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=15', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--network_dim=32', '--network_alpha=32', '--output_name=starwanqian', '--train_batch_size=2', '--save_every_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--xformers', '--shuffle_caption', '--use_8bit_adam']' returned non-zero exit status 1.

**Comment by Akegarasu** [comment]
![}_G1E$8X 5`~ B{X8E1FU0P](https://user-images.githubusercontent.com/36563862/221356583-d95e92fe-8455-4e32-a508-a59266b2d758.jpg)

**Comment by farcloudy** [comment]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\lora-scripts\sd-scripts\train_network.py", line 497, in <module>
    train(args)
  File "D:\stable-diffusion-webui\lora-scripts\sd-scripts\train_network.py", line 56, in train
    tokenizer = train_util.load_tokenizer(args)
  File "D:\stable-diffusion-webui\lora-scripts\sd-scripts\library\train_util.py", line 1797, in load_tokenizer
    tokenizer = CLIPTokenizer.from_pretrained(TOKENIZER_PATH)
  File "D:\stable-diffusion-webui\lora-scripts\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1804, in from_pretrained
    return cls._from_pretrained(
  File "D:\stable-diffusion-webui\lora-scripts\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1959, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "D:\stable-diffusion-webui\lora-scripts\venv\lib\site-packages\transformers\models\clip\tokenization_clip.py", line 323, in __init__
    self.encoder = json.load(vocab_handle)
  File "E:\anaconda3\envs\sd\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "E:\anaconda3\envs\sd\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "E:\anaconda3\envs\sd\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\anaconda3\envs\sd\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 125478 (char 125477)
Traceback (most recent call last):
  File "E:\anaconda3\envs\sd\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\anaconda3\envs\sd\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\stable-diffusion-webui\lora-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\stable-diffusion-webui\lora-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\stable-diffusion-webui\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\stable-diffusion-webui\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\stable-diffusion-webui\\lora-scripts\\venv\\Scripts\\python.exe', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=D:/stable-diffusion-webui/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors', '--train_data_dir=./train/aki', '--output_dir=./output', '--logging_dir=./logs', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=10', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--network_dim=32', '--network_alpha=32', '--output_name=aki', '--train_batch_size=1', '--save_every_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--xformers', '--shuffle_caption', '--use_8bit_adam']' returned non-zero exit status 1.

**Comment by Akegarasu** [comment]
clip模型下坏了，自己清掉旧的。huggingface/hub 目录

**Comment by timlee0719** [comment]
> clip模型下坏了，自己清掉旧的。huggingface/hub 目录

請問可以講解一下嗎? 我也是預到同樣的情況

**Comment by timlee0719** [comment]
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "C:\Users\TIM\kohya_ss\train_network.py", line 507, in <module>
    train(args)
  File "C:\Users\TIM\kohya_ss\train_network.py", line 150, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\Users\TIM\kohya_ss\library\train_util.py", line 1536, in get_optimizer
    assert optimizer_type is None or optimizer_type == "", "both option use_8bit_adam and optimizer_type are specified / use_8bit_adamとoptimizer_typeの両方のオプションが指定されています"
AssertionError: both option use_8bit_adam and optimizer_type are specified / use_8bit_adamとoptimizer_typeの両方のオプションが指定されています
Traceback (most recent call last):
  File "C:\Users\TIM\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\TIM\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\TIM\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\TIM\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\TIM\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\TIM\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\TIM\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=C:/AI Art/stable-diffusion-webui/models/Stable-diffusion/anything-v3-full.safetensors', '--train_data_dir=C:/AI Art/Training/Nikke_Marian/Destination', '--resolution=512,512', '--output_dir=C:/AI Art/Training/Nikke_Marian/Model', '--logging_dir=', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Nikke_Marian', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=800', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--use_8bit_adam', '--bucket_no_upscale']' returned non-zero exit status 1.
