### ISSUE TITLE
训练报错：ImportError: /lib64/libz.so.1: version `ZLIB_1.2.9' not found

### ISSUE THREAD

**Issue by duval1024** [Akegarasu/lora-scripts#125]
点击直接开始训练后报错：

```
Traceback (most recent call last):
  File "/data/home/duval1024/lora-scripts/./sd-scripts/train_network.py", line 17, in <module>
    import library.train_util as train_util
  File "/data/home/duval1024/lora-scripts/sd-scripts/library/train_util.py", line 56, in <module>
    import albumentations as albu
  File "/data/home/duval1024/lora-scripts/venv/lib/python3.10/site-packages/albumentations/__init__.py", line 5, in <module>
    from .augmentations import *
  File "/data/home/duval1024/lora-scripts/venv/lib/python3.10/site-packages/albumentations/augmentations/__init__.py", line 2, in <module>
    from .blur.functional import *
  File "/data/home/duval1024/lora-scripts/venv/lib/python3.10/site-packages/albumentations/augmentations/blur/__init__.py", line 1, in <module>
    from .functional import *
  File "/data/home/duval1024/lora-scripts/venv/lib/python3.10/site-packages/albumentations/augmentations/blur/functional.py", line 5, in <module>
    import cv2
  File "/data/home/duval1024/lora-scripts/venv/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/data/home/duval1024/lora-scripts/venv/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /data/home/duval1024/lora-scripts/venv/lib/python3.10/site-packages/cv2/../opencv_python.libs/libpng16-186fce2e.so.16.37.0)
```

**Comment by duval1024** [comment]
如果遇到上述问题，应该是linux共享库的zlib版本过低，升级到1.2.9版本即可：
1. http://www.zlib.net/fossils/ 下载1.2.9的zlib压缩包；
2. 解压 tar -xvf zlib-1.2.9.tar.gz && cd zlib-1.2.9
3. sudo -s # 进入root用户（务必执行这步且后续不能退出root，否则会导致sudo命令无法使用）
4.   ./configure && make && make install 
5.  根据你的报错信息里的路径删除原来so的文件软链接，比如我的例子是/lib64/libz.so.1。删除前务必确保第3步是正确的
6.  ln -s /usr/local/lib/libz.so.1.2.9 /lib64/libz.so.1  执行完这步应该就恢复正常了，这时候也可以退出root模式了。

**Comment by duval1024** [comment]
修正最开始的错误之后，又出现：

```
OSError: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found
```

查了下也是某个共享库过老，参考这文章的方法1或2解决：https://www.cnblogs.com/jimlau/p/13263052.html
