### ISSUE TITLE
安装过程有报错

### ISSUE THREAD

**Issue by Tyosei** [Akegarasu/lora-scripts#13]
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Tyo\Desktop\lora-scripts-main\lora-scripts-main\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\Tyo\Desktop\lora-scripts-main\lora-scripts-main\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\Tyo\Desktop\lora-scripts-main\lora-scripts-main\venv\lib\site-packages\pip\_internal\commands\install.py", line 461, in run
    installed = install_given_reqs(
  File "C:\Users\Tyo\Desktop\lora-scripts-main\lora-scripts-main\venv\lib\site-packages\pip\_internal\req\__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "C:\Users\Tyo\Desktop\lora-scripts-main\lora-scripts-main\venv\lib\site-packages\pip\_internal\req\req_install.py", line 790, in install
    install_wheel(
  File "C:\Users\Tyo\Desktop\lora-scripts-main\lora-scripts-main\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 727, in install_wheel
    _install_wheel(
  File "C:\Users\Tyo\Desktop\lora-scripts-main\lora-scripts-main\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 587, in _install_wheel
    file.save()
  File "C:\Users\Tyo\Desktop\lora-scripts-main\lora-scripts-main\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 388, in save
    shutil.copyfileobj(f, dest)
  File "C:\Users\Tyo\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Users\Tyo\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 925, in read
    data = self._read1(n)
  File "C:\Users\Tyo\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1015, in _read1
    self._update_crc(data)
  File "C:\Users\Tyo\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 943, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/cusolver64_11.dll'

[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by Akegarasu** [comment]
尝试重新安装
