### ISSUE TITLE
 TypeError: Input must be callable

### ISSUE THREAD

**Issue by pythonsuperman886** [Akegarasu/lora-scripts#136]
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "./sd-scripts/train_network.py", line 20, in <module>
    import library.config_util as config_util
  File "/home/wangwei/project/experiment/lora-scripts/sd-scripts/library/config_util.py", line 113, in <module>
    class ConfigSanitizer:
  File "/home/wangwei/project/experiment/lora-scripts/sd-scripts/library/config_util.py", line 116, in ConfigSanitizer
    def __validate_and_convert_twodim(klass, value: Sequence) -> Tuple:
  File "/home/wangwei/envs/anaconda3/envs/diffusers/lib/python3.8/site-packages/toolz/functoolz.py", line 142, in __init__
    raise TypeError("Input must be callable")
TypeError: Input must be callable
Traceback (most recent call last):
  File "/home/wangwei/envs/anaconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/wangwei/envs/anaconda3/envs/diffusers/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/wangwei/envs/anaconda3/envs/diffusers/lib/python3.8/site-packages/accelerate/commands/launch.py", line 919, in launch_command
    simple_launcher(args)
  File "/home/wangwei/envs/anaconda3/envs/diffusers/lib/python3.8/site-packages/accelerate/commands/launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/wangwei/envs/anaconda3/envs/diffusers/bin/python3.8', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=/home/wangwei/project/experiment/lora-scripts/v1-5-pruned-emaonly.ckpt', '--train_data_dir=/home/wangwei/project/experiment/lora-scripts/sd-scripts/images', '--output_dir=./output', '--logging_dir=./logs', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=20', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=niaoren', '--train_batch_size=1', '--save_every_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--xformers', '--shuffle_caption', '--reg_data_dir', '/home/wangwei/project/experiment/lora-scripts/sd-scripts/images', '--use_8bit_adam']' returned non-zero exit status 1.

**Comment by martellz** [comment]
try this
https://github.com/kohya-ss/sd-scripts/issues/253#issuecomment-1452960863

**Comment by Akegarasu** [comment]
use python 3.10
