### ISSUE TITLE
4070一直无法运行

### ISSUE THREAD

**Issue by 2569450780** [Akegarasu/lora-scripts#14]
取消8 bit adam也没办法使用

prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
Traceback (most recent call last):
  File "D:\AI\developer\lora\lora-scripts\sd-scripts\train_network.py", line 548, in <module>
    train(args)
  File "D:\AI\developer\lora\lora-scripts\sd-scripts\train_network.py", line 156, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "D:\AI\developer\lora\lora-scripts\sd-scripts\library\train_util.py", line 1584, in load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.pretrained_model_name_or_path)
  File "D:\AI\developer\lora\lora-scripts\sd-scripts\library\model_util.py", line 877, in load_models_from_stable_diffusion_checkpoint
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(v2, state_dict, unet_config)
  File "D:\AI\developer\lora\lora-scripts\sd-scripts\library\model_util.py", line 234, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'
Traceback (most recent call last):
  File "C:\Users\XIE\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\XIE\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AI\developer\lora\lora-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\AI\developer\lora\lora-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\AI\developer\lora\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\AI\developer\lora\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\AI\\developer\\lora\\lora-scripts\\venv\\Scripts\\python.exe', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=./sd-models/koreanDollLikeness_v15.safetensors', '--train_data_dir=./train/donghan', '--output_dir=./output', '--logging_dir=./logs', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=15', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--network_dim=32', '--network_alpha=32', '--output_name=donghan', '--train_batch_size=1', '--save_every_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=512', '--max_bucket_reso=512']' returned non-zero exit status 1.
Train finished

**Comment by Akegarasu** [comment]
底模有问题
