### ISSUE TITLE
直接读取的保存数值。从昨天开始就无法训练一直失败了。

### ISSUE THREAD

**Issue by WEIAUTUMN918** [Akegarasu/lora-scripts#143]
[Dataset 0]
loading image sizes.
100%|███████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 624.32it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (768, 768), count: 250
mean ar error (without repeats): 0.0
prepare accelerator
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint: ./sd-models/chilloutmix_NiPrunedFp32Fix.safetensors
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
CrossAttention.forward has been replaced to enable xformers.
[Dataset 0]
caching latents.
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.59it/s]
import network module: networks.lora
create LoRA network. base dim (rank): 128, alpha: 64
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
Traceback (most recent call last):
  File "E:\loraqiuye\sd-scripts\train_network.py", line 783, in <module>
    train(args)
  File "E:\loraqiuye\sd-scripts\train_network.py", line 194, in train
    info = network.load_weights(args.network_weights)
  File "E:\loraqiuye\sd-scripts\networks\lora.py", line 803, in load_weights
    weights_sd = torch.load(file, map_location="cpu")
  File "E:\loraqiuye\python\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\loraqiuye\python\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\loraqiuye\python\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "E:\loraqiuye\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\loraqiuye\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\loraqiuye\python\lib\site-packages\accelerate\commands\launch.py", line 1114, in <module>
    main()
  File "E:\loraqiuye\python\lib\site-packages\accelerate\commands\launch.py", line 1110, in main
    launch_command(args)
  File "E:\loraqiuye\python\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "E:\loraqiuye\python\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\loraqiuye\\python\\python.exe', './sd-scripts/train_network.py', '--config_file', 'E:\\loraqiuye\\toml\\autosave\\20230605-025734.toml']' returned non-zero exit status 1.
Training failed / 训练失败

**Comment by WEIAUTUMN918** [comment]
> _未提供描述。_

**Comment by rq233** [comment]
我也遇到这个问题了，hxd有解决吗

**Comment by Twoone94** [comment]
俺也一样

**Comment by Twoone94** [comment]
刚试了下，好像解决了 。


FileNotFoundError: [Errno 2] No such file or directory: '我查了下翻译，说是找不到这个文档文件，就去查了下设置问题。

解决方法：
我改成了专家模式（虽然我是个菜鸟...）

- pretrained_model_name_or_path(底模文件路径)：我放在 LORA训练文件的“E:\lora-scripts-v1.5.1\sd-models\realisticVisionV51_v51VAE.safetensors”,。

- train_data_dir(训练数据集路径)：路径填写不要放在  例如：E:\lora-scripts-v1.5.1\train\girl\20_girl。要放在：E:\lora-scripts-v1.5.1\train\gir

- **OUTPUT_DIR（模型保存文件）：是需要填写的！！！填写无中文！！！**

------如有错误请指出，感谢大佬！！------
