### ISSUE TITLE
又报错，感觉是CUDA问题，但是有看不出来，请教大佬看看

### ISSUE THREAD

**Issue by plhys** [Akegarasu/lora-scripts#159]
steps:   0%|                                                                                                                                                                         | 0/1500 [00:00<?, ?it/s]
epoch 1/10
Traceback (most recent call last):
  File "/root/lora-scripts/./sd-scripts/train_network.py", line 783, in <module>
    train(args)
  File "/root/lora-scripts/./sd-scripts/train_network.py", line 610, in train
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/accelerate/utils/operations.py", line 490, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 381, in forward
    sample, res_samples = downsample_block(
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 612, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/diffusers/models/attention.py", line 216, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/diffusers/models/attention.py", line 484, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/lora-scripts/sd-scripts/library/train_util.py", line 1846, in forward_xformers
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)  # 最適なのを選んでくれる
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/xformers/ops/memory_efficient_attention.py", line 975, in memory_efficient_attention
    return op.apply(query, key, value, attn_bias, p, scale).reshape(output_shape)
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/xformers/ops/memory_efficient_attention.py", line 360, in forward
    out, lse = cls.FORWARD_OPERATOR(
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
steps:   0%|                                                                                                                                                                         | 0/1500 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/root/miniconda3/envs/lora/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/lora/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1114, in <module>
    main()
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1110, in main
    launch_command(args)
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/envs/lora/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/lora/bin/python', './sd-scripts/train_network.py', '--config_file', '/root/lora-scripts/toml/autosave/20230621-135115.toml']' returned non-zero exit status 1.
Training failed / 训练失败

**Comment by Georgebillion** [comment]
训练环境提供一下，另外说一下CUDA版本号

**Comment by Akegarasu** [comment]
xformers的问题，如果你是3090参考我bash脚本里的特定版本安装
