### ISSUE TITLE
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...

### ISSUE THREAD

**Issue by paysenyu** [Akegarasu/lora-scripts#16]
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
Traceback (most recent call last):
  File "D:\AI\lora-scripts\sd-scripts\train_network.py", line 497, in <module>
    train(args)
  File "D:\AI\lora-scripts\sd-scripts\train_network.py", line 150, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "D:\AI\lora-scripts\sd-scripts\library\train_util.py", line 1566, in get_optimizer
    import bitsandbytes as bnb
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\site-packages\bitsandbytes\cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\site-packages\bitsandbytes\cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\site-packages\bitsandbytes\cextension.py", line 31, in initialize
    self.lib = ct.cdll.LoadLibrary(binary_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3108\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python3108\\python.exe', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=./sd-models/goodAsianGirlFaceV10_goodasiangirlfaceV10.safetensors', '--train_data_dir=./train/shishi', '--output_dir=./output', '--logging_dir=./logs', '--resolution=768,1024', '--network_module=networks.lora', '--max_train_epochs=20', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--network_dim=64', '--network_alpha=32', '--output_name=liushishi', '--train_batch_size=3', '--save_every_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--xformers', '--shuffle_caption', '--use_8bit_adam']' returned non-zero exit status 1.
Train finished

**Comment by paysenyu** [comment]
I tried to download cuda 11.6 on NVDIA, but still doesn`t work

![image](https://user-images.githubusercontent.com/51367628/222057465-c6779187-66ae-4c79-a353-bbf7bd8b9e18.png)

**Comment by Akegarasu** [comment]
what‘s your graphics card model?

**Comment by paysenyu** [comment]
> what‘s your graphics card model?

RTX 3090

**Comment by Akegarasu** [comment]
try delete venv then run install script again.

**Comment by Song950106** [comment]
I have this problem too，with GTX 1080ti. 
Is this card able to satisfy the training?

**Comment by Akegarasu** [comment]
GTX 10 series are not satisfy working with 8bitadam. Change `use_8bit_adam` to 0.

**Comment by k23223** [comment]
查看这个：https://github.com/kohya-ss/sd-scripts/issues/598
我是用pip install bitsandbytes-windows这个命令就解决该问题了，显卡是rtx 3060 笔记本
