### ISSUE TITLE
ModuleNotFoundError: No module named 'jmespath'，秋叶大佬做的整合包我都用不了

### ISSUE THREAD

**Issue by Feige-cn** [Akegarasu/lora-scripts#168]
使用目录内的 python 进行启动....
Starting tensorboard...
Server started at http://127.0.0.1:28000
TensorBoard 2.10.1 at http://127.0.0.1:6006/ (Press CTRL+C to quit)
Training started with config file / 训练开始，使用配置文件: D:\lora-scripts-gui\toml\autosave\20230626-170156.toml
Traceback (most recent call last):
  File "D:\lora-scripts-gui\python\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\lora-scripts-gui\python\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\lora-scripts-gui\python\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "D:\lora-scripts-gui\python\lib\site-packages\accelerate\accelerator.py", line 27, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "D:\lora-scripts-gui\python\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "D:\lora-scripts-gui\python\lib\site-packages\accelerate\utils\__init__.py", line 122, in <module>
    from .other import (
  File "D:\lora-scripts-gui\python\lib\site-packages\accelerate\utils\other.py", line 20, in <module>
    from ..commands.config.default import write_basic_config  # noqa: F401
  File "D:\lora-scripts-gui\python\lib\site-packages\accelerate\commands\config\__init__.py", line 19, in <module>
    from .config import config_command_parser
  File "D:\lora-scripts-gui\python\lib\site-packages\accelerate\commands\config\config.py", line 25, in <module>
    from .sagemaker import get_sagemaker_input
  File "D:\lora-scripts-gui\python\lib\site-packages\accelerate\commands\config\sagemaker.py", line 34, in <module>
    import boto3  # noqa: F401
  File "C:\Users\H\AppData\Roaming\Python\Python310\site-packages\boto3\__init__.py", line 17, in <module>
    from boto3.session import Session
  File "C:\Users\H\AppData\Roaming\Python\Python310\site-packages\boto3\session.py", line 17, in <module>
    import botocore.session
  File "C:\Users\H\AppData\Roaming\Python\Python310\site-packages\botocore\session.py", line 26, in <module>
    import botocore.client
  File "C:\Users\H\AppData\Roaming\Python\Python310\site-packages\botocore\client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "C:\Users\H\AppData\Roaming\Python\Python310\site-packages\botocore\waiter.py", line 16, in <module>
    import jmespath
ModuleNotFoundError: No module named 'jmespath'
Training failed / 训练失败

**Comment by Feige-cn** [comment]
> ?检查虚拟环境的依赖是否全部安装，重新运行一下install-cn.ps1

肯定是环境的问题，但是重新运行install并不解决问题，不知道这个jmespath为什么报错，我的pip list里面明明有这个。
前段时间想用秋叶的SD模型整合包，也是遇到同样的问题。后来只能放弃整合包自己配置了

**Comment by Akegarasu** [comment]
更新
