### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by hopeyan476868** [Akegarasu/lora-scripts#177]
lunix 错误提示：
 File "/data3/design/public/stable-diffusion-webui-11/lora-scripts/./sd-scripts/train_network.py", line 873, in <module>
    train(args)
  File "/data3/design/public/stable-diffusion-webui-11/lora-scripts/./sd-scripts/train_network.py", line 766, in train
    train_util.sample_images(accelerator, args, epoch + 1, global_step, accelerator.device, vae, tokenizer, text_encoder, unet)
  File "/data3/design/public/stable-diffusion-webui-11/lora-scripts/sd-scripts/library/train_util.py", line 3480, in sample_images
    if not os.path.isfile(args.sample_prompts):
  File "/data3/design/.conda/envs/nox/lib/python3.10/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneTypeypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

steps:   6%|▋         | 27/432 [01:45<26:21,  3.91s/it, loss=0.0677]
Traceback (most recent call last):
  File "/data3/design/.conda/envs/nox/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data3/design/.conda/envs/nox/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data3/design/public/stable-diffusion-webui-11/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1114, in <module>
    main()
  File "/data3/design/public/stable-diffusion-webui-11/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1110, in main
    launch_command(args)
  File "/data3/design/public/stable-diffusion-webui-11/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/data3/design/public/stable-diffusion-webui-11/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/data3/design/public/stable-diffusion-webui-11/lora-scripts/venv/bin/python', './sd-scripts/train_network.py', '--config_file', '/data3/design/public/stable-diffusion-webui-11/lora-scripts/toml/autosave/20230715-070545.toml']' returned non-zero exit status 1.
chevron_right

**Comment by hopeyan476868** [comment]
solved
