### ISSUE TITLE
FileNotFoundError: Could not find module

### ISSUE THREAD

**Issue by glowstone314** [Akegarasu/lora-scripts#188]
CUDA SETUP: Loading binary D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
Traceback (most recent call last):
  File "D:\stable diffusion\lora-scripts-gui\python\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\stable diffusion\lora-scripts-gui\python\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\DW\AppData\Roaming\Python\Python310\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\DW\AppData\Roaming\Python\Python310\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Users\DW\AppData\Roaming\Python\Python310\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Users\DW\AppData\Roaming\Python\Python310\site-packages\accelerate\utils\__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "C:\Users\DW\AppData\Roaming\Python\Python310\site-packages\accelerate\utils\bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\cextension.py", line 43, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\cextension.py", line 39, in get_instance
    cls._instance.initialize()
  File "D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\cextension.py", line 33, in initialize
    self.lib = ct.cdll.LoadLibrary(str(binary_path))            # $$$
  File "D:\stable diffusion\lora-scripts-gui\python\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "D:\stable diffusion\lora-scripts-gui\python\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Training failed / 训练失败

**Comment by wanjunling168** [comment]
install bitsandbytes from https://github.com/jllllll/bitsandbytes-windows-webui

**Comment by jcplus** [comment]
我也遇到过这个错误，在train.sh前面加上`pip install bitsandbytes`后解决了

**Comment by Akegarasu** [comment]
install bitsandbytes for windows
