### ISSUE TITLE
手贱想把文件从D盘换到H盘就发生错误了

### ISSUE THREAD

**Issue by q765647578** [Akegarasu/lora-scripts#191]
使用目录内的 python 进行启动....
Starting tensorboard...
Server started at http://127.0.0.1:28000
TensorBoard 2.10.1 at http://127.0.0.1:6006/ (Press CTRL+C to quit)
Training started with config file / 训练开始，使用配置文件: D:\Program Files\lora-scripts-gui\toml\autosave\20230730-054855.toml
Loading settings from D:\Program Files\lora-scripts-gui\toml\autosave\20230730-054855.toml...
D:\Program Files\lora-scripts-gui\toml\autosave\20230730-054855
prepare tokenizer
update token length: 255
Using DreamBooth method.
prepare images.
found directory H:\lora-scripts-gui\train\cyborg\train\25_cyborg contains 47 image files
found directory H:\lora-scripts-gui\train\cyborg\reg\2_cyborg contains 71 image files
No caption file found for 71 images. Training will continue without captions for these images. If class token exists, it will be used. / 71枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を 続行します。class tokenが存在する場合はそれを使います。
H:\lora-scripts-gui\train\cyborg\reg\2_cyborg\0404f323045628d77af2828b5448c91c.png
H:\lora-scripts-gui\train\cyborg\reg\2_cyborg\072a10d1dea3f78a86e94d3ec5445198.jpg
H:\lora-scripts-gui\train\cyborg\reg\2_cyborg\0826fc151fc234273ce632c0db431d9f.jpg
H:\lora-scripts-gui\train\cyborg\reg\2_cyborg\0_0.png
H:\lora-scripts-gui\train\cyborg\reg\2_cyborg\0a9ec075a05499d887bd772c5c6934df.jpg
H:\lora-scripts-gui\train\cyborg\reg\2_cyborg\0ea6be87d9520d7ea59a2e206e68ec43.jpg... and 66 more
1175 train images with repeating.
142 reg images.
[Dataset 0]
  batch_size: 2
  resolution: (512, 768)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "H:\lora-scripts-gui\train\cyborg\train\25_cyborg"
    image_count: 47
    num_repeats: 25
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: cyborg
    caption_extension: .txt

  [Subset 1 of Dataset 0]
    image_dir: "H:\lora-scripts-gui\train\cyborg\reg\2_cyborg"
    image_count: 71
    num_repeats: 2
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: True
    class_tokens: cyborg
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|███████████████████████████████████████████████████████████████████████████████| 118/118 [00:01<00:00, 113.86it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (448, 832), count: 513
bucket 1: resolution (512, 704), count: 300
bucket 2: resolution (512, 768), count: 1537
mean ar error (without repeats): 0.011652529128117125
preparing accelerator
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint: H:/SD/sd-webui-aki-v4.1/models/Stable-diffusion/v1-5-pruned.ckpt
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
CrossAttention.forward has been replaced to enable xformers.
import network module: networks.lora
[Dataset 0]
caching latents.
100%|████████████████████████████████████████████████████████████████████████████████| 118/118 [00:58<00:00,  2.02it/s]
create LoRA network. base dim (rank): 128, alpha: 64
neuron dropout: p=0, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
Traceback (most recent call last):
  File "D:\Program Files\lora-scripts-gui\sd-scripts\train_network.py", line 873, in <module>
    train(args)
  File "D:\Program Files\lora-scripts-gui\sd-scripts\train_network.py", line 242, in train
    info = network.load_weights(args.network_weights)
  File "D:\Program Files\lora-scripts-gui\sd-scripts\networks\lora.py", line 882, in load_weights
    weights_sd = torch.load(file, map_location="cpu")
  File "D:\Program Files\lora-scripts-gui\python\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Program Files\lora-scripts-gui\python\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Program Files\lora-scripts-gui\python\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "D:\Program Files\lora-scripts-gui\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\lora-scripts-gui\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 1114, in <module>
    main()
  File "D:\Program Files\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 1110, in main
    launch_command(args)
  File "D:\Program Files\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\Program Files\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Program Files\\lora-scripts-gui\\python\\python.exe', './sd-scripts/train_network.py', '--config_file', 'D:\\Program Files\\lora-scripts-gui\\toml\\autosave\\20230730-054855.toml']' returned non-zero exit status 1.
Training failed / 训练失败
E0730 05:55:11.623730  3128 _internal.py:186] 127.0.0.1 - - [30/Jul/2023 05:55:11] code 400, message Bad request version ('7ÕL\xadåXQÑì\x84\x0e°³')
E0730 05:55:11.906973 13104 _internal.py:186] 127.0.0.1 - - [30/Jul/2023 05:55:11] code 400, message Bad request version ('zz\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93ÚÚ\x00\x00\x00-\x00\x02\x01\x01ÿ\x01\x00\x01\x00\x00+\x00\x07\x06\x9a\x9a\x03\x04\x03\x03\x00#\x00\x00\x00\x12\x00\x00\x00')

**Comment by q765647578** [comment]
如何解决  跪倒
