### ISSUE TITLE
用青龙最新的sdxl的脚本覆盖原有的sd-script, 按之前的参数练sd1.5的lora报错

### ISSUE THREAD

**Issue by cccancc** [Akegarasu/lora-scripts#194]
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 280
mean ar error (without repeats): 0.0
preparing accelerator
Traceback (most recent call last):
  File "C:\lora train\lora训练界面\sd-scripts\train_network.py", line 990, in <module>
    trainer.train(args)
  File "C:\lora train\lora训练界面\sd-scripts\train_network.py", line 206, in train
    accelerator = train_util.prepare_accelerator(args)
  File "C:\lora train\lora训练界面\sd-scripts\library\train_util.py", line 3575, in prepare_accelerator
    accelerator = Accelerator(
TypeError: Accelerator.__init__() got an unexpected keyword argument 'project_dir'
Traceback (most recent call last):
  File "C:\lora train\lora训练界面\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\lora train\lora训练界面\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\lora train\lora训练界面\python\lib\site-packages\accelerate\commands\launch.py", line 1114, in <module>
    main()
  File "C:\lora train\lora训练界面\python\lib\site-packages\accelerate\commands\launch.py", line 1110, in main
    launch_command(args)
  File "C:\lora train\lora训练界面\python\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\lora train\lora训练界面\python\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\lora train\\lora训练界面\\python\\python.exe', './sd-scripts/train_network.py', '--config_file', 'C:\\lora train\\lora训练界面\\toml\\autosave\\20230731-185534.toml']' returned non-zero exit status 1.
Training failed / 训练失败

**Comment by wanjunling168** [comment]
package `accelerate` 's version incorrect
accelerate包版本不对，检查版本，0.18.x后才有 `project_dir` 这个参数，在那之前是 `logging_dir`

**Comment by cccancc** [comment]
好的 了解 谢谢

**Comment by terence-wu** [comment]
想问下sd的text2img api，lora参数是传哪个字段
