### ISSUE TITLE
升级1.5后报错

### ISSUE THREAD

**Issue by Kanou911** [Akegarasu/lora-scripts#206]
create LoRA network. base dim (rank): 64, alpha: 64
neuron dropout: p=0, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
use Lion optimizer | {}
override steps. steps for 18 epochs is / 指定エポックまでのステップ数: 4662
Traceback (most recent call last):
  File "G:\lora-scripts-gui\sd-scripts\train_network.py", line 990, in <module>
    trainer.train(args)
  File "G:\lora-scripts-gui\sd-scripts\train_network.py", line 353, in train
    lr_scheduler = train_util.get_scheduler_fix(args, optimizer, accelerator.num_processes)
  File "G:\lora-scripts-gui\sd-scripts\library\train_util.py", line 3584, in get_scheduler_fix
    if name == SchedulerType.PIECEWISE_CONSTANT:
  File "G:\lora-scripts-gui\python\lib\enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: PIECEWISE_CONSTANT
Traceback (most recent call last):
  File "G:\lora-scripts-gui\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "G:\lora-scripts-gui\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 928, in <module>
    main()
  File "G:\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 924, in main
    launch_command(args)
  File "G:\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 918, in launch_command
    simple_launcher(args)
  File "G:\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 580, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['G:\\lora-scripts-gui\\python\\python.exe', './sd-scripts/train_network.py', '--config_file', 'G:\\lora-scripts-gui\\toml\\autosave\\20230813-004446.toml']' returned non-zero exit status 1.
Training failed / 训练失败

**Comment by Akegarasu** [comment]
更新

**Comment by akk-123** [comment]
@Kanou911 遇到同样的问题，你怎么解决的
