### ISSUE TITLE
ModuleNotFoundError: No module named 'lion_pytorch'

### ISSUE THREAD

**Issue by shookgao** [Akegarasu/lora-scripts#23]
用`8bit-adam`可以正常训练，使用`lion`训练就提示错误，请问如何处理？具体错误描述如下：
```bash
Traceback (most recent call last):
  File "D:\mys\tools\Lora\sd-scripts\library\train_util.py", line 1593, in get_optimizer
    import lion_pytorch
ModuleNotFoundError: No module named 'lion_pytorch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\mys\tools\Lora\sd-scripts\train_network.py", line 507, in <module>
    train(args)
  File "D:\mys\tools\Lora\sd-scripts\train_network.py", line 150, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "D:\mys\tools\Lora\sd-scripts\library\train_util.py", line 1595, in get_optimizer
    raise ImportError("No lion_pytorch / lion_pytorch がインストールされていないようです")
ImportError: No lion_pytorch / lion_pytorch がインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\iamgb\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\iamgb\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\mys\tools\Lora\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\mys\tools\Lora\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\mys\tools\Lora\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\mys\tools\Lora\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\mys\\tools\\Lora\\venv\\Scripts\\python.exe', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=./sd-models/model.ckpt', '--train_data_dir=./train', '--output_dir=./output', '--logging_dir=./logs', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=10', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=64', '--network_alpha=64', '--output_name=ZhangJiani', '--train_batch_size=1', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--xformers', '--shuffle_caption', '--network_train_unet_only', '--use_lion_optimizer']' returned non-zero exit status 1.
Train finished
```

**Comment by Akegarasu** [comment]
使用lion需要重新运行一遍安装脚本以补全依赖

**Comment by shookgao** [comment]
> 使用lion需要重新运行一遍安装脚本以补全依赖

回复好快啊！我刚才也想到这个问题了，我开始安装了一次，然后进行了更新，有了新的选项，但没想到还要再安装一次，现在重新执行了一次安装程序，已经可以正常训练了，谢谢！
