### ISSUE TITLE
--stop_text_encoder_training=0报错

### ISSUE THREAD

**Issue by yyyhainan** [Akegarasu/lora-scripts#231]
在终端运行`powershell.exe train.ps1`
运行结果如下：
```
前面是一堆参数，接着
train_network.py: error: unrecognized arguments: --stop_text_encoder_training=
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\lo\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\anaconda3\envs\lo\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\anaconda3\envs\lo\lib\site-packages\accelerate\commands\launch.py", line 996, in <module>
    main()
  File "C:\Users\admin\anaconda3\envs\lo\lib\site-packages\accelerate\commands\launch.py", line 992, in main
    launch_command(args)
  File "C:\Users\admin\anaconda3\envs\lo\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Users\admin\anaconda3\envs\lo\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\admin\\anaconda3\\envs\\lo\\python.exe', './sd-scripts/train_network.
py', '--enable_bucket', '--pretrained_model_name_or_path=C:/Users/admin/Desktop/yyy/lora-scripts/sd-models/model.safetenso
rs', '--train_data_dir=C:/Users/admin/Desktop/yyy/lora-scripts/train/satono', '--output_dir=./output', '--logging_dir=./lo
gs', '--log_prefix=aki', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=30', '--learning_ra
te=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_
scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=aki', '--train_batch_size=1', '--save_ev
ery_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--prior_loss_weight
=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_
bucket_reso=1024', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--clip_skip=2', '--stop_text_encoder_training=',
 '--min_snr_gamma=0', '--log_with=tensorboard']' returned non-zero exit status 2.
Train finished
```
--stop_text_encoder_training=这个参数直接设置为0也不行，可是不设置这个参数就会有其他的错误
if ($stop_text_encoder_training -ne 0) {
  [void]$ext_args.Add("--stop_text_encoder_training=0")
}

**Comment by yyyhainan** [comment]
当删除--stop_text_encoder_training这个参数，情况如下：
```
[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████
████████████████████████| 32/32 [00:00<00:00, 2047.44it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 192
mean ar error (without repeats): 0.0
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: C:/Users/admin/Desktop/yyy/lora-scripts/sd-models/model.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\yyy\lora-scripts\sd-scripts\train_network.py", line 990, in <module>
    trainer.train(args)
  File "C:\Users\admin\Desktop\yyy\lora-scripts\sd-scripts\train_network.py", line 214, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "C:\Users\admin\Desktop\yyy\lora-scripts\sd-scripts\train_network.py", line 91, in load_target_model
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "C:\Users\admin\Desktop\yyy\lora-scripts\sd-scripts\library\train_util.py", line 3865, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "C:\Users\admin\Desktop\yyy\lora-scripts\sd-scripts\library\train_util.py", line 3808, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(
  File "C:\Users\admin\Desktop\yyy\lora-scripts\sd-scripts\library\model_util.py", line 1065, in load_models_from_stable_d
iffusion_checkpoint
    info = text_model.load_state_dict(converted_text_encoder_checkpoint)
  File "C:\Users\admin\anaconda3\envs\lo\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Unexpected key(s) in state_dict: "text_model.embeddings.position_ids".
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\lo\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\anaconda3\envs\lo\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\anaconda3\envs\lo\lib\site-packages\accelerate\commands\launch.py", line 996, in <module>
    main()
  File "C:\Users\admin\anaconda3\envs\lo\lib\site-packages\accelerate\commands\launch.py", line 992, in main
    launch_command(args)
  File "C:\Users\admin\anaconda3\envs\lo\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Users\admin\anaconda3\envs\lo\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\admin\\anaconda3\\envs\\lo\\python.exe', './sd-scripts/train_network.
py', '--enable_bucket', '--pretrained_model_name_or_path=C:/Users/admin/Desktop/yyy/lora-scripts/sd-models/model.safetenso
rs', '--train_data_dir=C:/Users/admin/Desktop/yyy/lora-scripts/train/satono', '--output_dir=./output', '--logging_dir=./lo
gs', '--log_prefix=aki', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=30', '--learning_ra
te=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_
scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=aki', '--train_batch_size=1', '--save_ev
ery_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--prior_loss_weight
=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_
bucket_reso=1024', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--clip_skip=2', '--min_snr_gamma=0', '--log_with
=tensorboard']' returned non-zero exit status 1.
Train finished
```

**Comment by wenHK** [comment]
> stop_text_encoder_training

请问要怎么解决

**Comment by yyyhainan** [comment]
因为我是自己安装的环境，没用它那个install脚本，后来`bash run_gui.sh`，它自动补充了很多环境，就可以了，实在不放心的还可以换个sd的主模型
