### ISSUE TITLE
最新版训练失败，跑了100多步训练不了了

### ISSUE THREAD

**Issue by RexLeeGrey** [Akegarasu/lora-scripts#245]
raceback (most recent call last):
  File "D:\AIGC\lora-scripts-gui\sd-scripts\train_network.py", line 990, in <module>
    trainer.train(args)
  File "D:\AIGC\lora-scripts-gui\sd-scripts\train_network.py", line 730, in train
    for step, batch in enumerate(train_dataloader):
  File "D:\AIGC\lora-scripts-gui\python\lib\site-packages\accelerate\data_loader.py", line 388, in __iter__
    next_batch = next(dataloader_iter)
  File "D:\AIGC\lora-scripts-gui\python\lib\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "D:\AIGC\lora-scripts-gui\python\lib\site-packages\torch\utils\data\dataloader.py", line 1326, in _next_data
    return self._process_data(data)
  File "D:\AIGC\lora-scripts-gui\python\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "D:\AIGC\lora-scripts-gui\python\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "D:\AIGC\lora-scripts-gui\python\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\AIGC\lora-scripts-gui\python\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\AIGC\lora-scripts-gui\python\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\AIGC\lora-scripts-gui\python\lib\site-packages\torch\utils\data\dataset.py", line 243, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "D:\AIGC\lora-scripts-gui\sd-scripts\library\train_util.py", line 1222, in __getitem__
    example["latents"] = torch.stack(latents_list) if latents_list[0] is not None else None
RuntimeError: stack expects each tensor to be equal size, but got [4, 112, 80] at entry 0 and [4, 104, 88] at entry 4

steps:   0%|▏                                                         | 123/31520 [01:47<7:37:42,  1.14it/s, loss=0.14]
Traceback (most recent call last):
  File "D:\AIGC\lora-scripts-gui\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\AIGC\lora-scripts-gui\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AIGC\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 928, in <module>
    main()
  File "D:\AIGC\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 924, in main
    launch_command(args)
  File "D:\AIGC\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 918, in launch_command
    simple_launcher(args)
  File "D:\AIGC\lora-scripts-gui\python\lib\site-packages\accelerate\commands\launch.py", line 580, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\AIGC\\lora-scripts-gui\\python\\python.exe', './sd-scripts/train_network.py', '--config_file', 'D:\\AIGC\\lora-scripts-gui\\config\\autosave\\20230923-022108.toml']' returned non-zero exit status 1.

**Comment by RexLeeGrey** [comment]
同样的设置和数据集在kohya上可以跑

**Comment by Akegarasu** [comment]
https://github.com/kohya-ss/sd-scripts/issues/522
