### ISSUE TITLE
训练失败 KeyError: 'encoder.norm_out.weight'

### ISSUE THREAD

**Issue by xys20071111** [Akegarasu/lora-scripts#248]
平台：AutoDL  
镜像版本：v13
报错信息  
```
Traceback (most recent call last):
  File "/root/lora-scripts/./sd-scripts/sdxl_train_network.py", line 176, in <module>
    trainer.train(args)
  File "/root/lora-scripts/sd-scripts/train_network.py", line 214, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "/root/lora-scripts/./sd-scripts/sdxl_train_network.py", line 37, in load_target_model
    ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, weight_dtype)
  File "/root/lora-scripts/sd-scripts/library/sdxl_train_util.py", line 34, in load_target_model
    ) = _load_target_model(
  File "/root/lora-scripts/sd-scripts/library/sdxl_train_util.py", line 124, in _load_target_model
    vae = model_util.load_vae(vae_path, weight_dtype)
  File "/root/lora-scripts/sd-scripts/library/model_util.py", line 1291, in load_vae
    converted_vae_checkpoint = convert_ldm_vae_checkpoint(vae_sd, vae_config)
  File "/root/lora-scripts/sd-scripts/library/model_util.py", line 411, in convert_ldm_vae_checkpoint
    new_checkpoint["encoder.conv_norm_out.weight"] = vae_state_dict["encoder.norm_out.weight"]
KeyError: 'encoder.norm_out.weight'
```
训练配置
```
pretrained_model_name_or_path = "./lora-scripts/sd-models/sd_xl_base_1.0.safetensors"
vae = "/root/autodl-tmp/diffusion_pytorch_model.safetensors"
v2 = false
train_data_dir = "***"
prior_loss_weight = 1
resolution = "1024,1024"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64
output_name = "***"
output_dir = "/root/autodl-tmp/output"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 1
max_train_epochs = 10
train_batch_size = 1
gradient_checkpointing = false
network_train_unet_only = false
network_train_text_encoder_only = false
learning_rate = 0.0001
unet_lr = 0.0001
text_encoder_lr = 1e-5
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "AdamW8bit"
network_module = "networks.lora"
network_dim = 32
network_alpha = 32
network_dropout = 0
sample_prompts = "/root/lora-scripts/config/autosave/20230925-194202-promopt.txt"
sample_sampler = "euler_a"
sample_every_n_epochs = 2
log_with = "tensorboard"
logging_dir = "/root/tf-logs"
caption_extension = ".txt"
shuffle_caption = true
weighted_captions = false
keep_tokens = 3
max_token_length = 255
seed = 1337
clip_skip = 2
mixed_precision = "fp16"
full_fp16 = false
full_bf16 = false
xformers = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = false
cache_text_encoder_outputs_to_disk = false
persistent_data_loader_workers = true

```

**Comment by xys20071111** [comment]
换成镜像里自带的vae模型就好了
