### ISSUE TITLE
TypeError: Input must be callable

### ISSUE THREAD

**Issue by Miloxing** [Akegarasu/lora-scripts#25]
/content/lora-scripts
Traceback (most recent call last):
  File "./sd-scripts/train_network.py", line 20, in <module>
    import library.config_util as config_util
  File "/content/lora-scripts/sd-scripts/library/config_util.py", line 113, in <module>
    class ConfigSanitizer:
  File "/content/lora-scripts/sd-scripts/library/config_util.py", line 116, in ConfigSanitizer
    def __validate_and_convert_twodim(klass, value: Sequence) -> Tuple:
  File "/usr/local/lib/python3.8/dist-packages/toolz/functoolz.py", line 201, in __init__
    raise TypeError("Input must be callable")
TypeError: Input must be callable
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=./sd-models/model.safetensors', '--train_data_dir=./train/aki', '--output_dir=./output', '--logging_dir=./logs', '--resolution=768,768', '--network_module=networks.lora', '--max_train_epochs=20', '--learning_rate=1e-4', '--unet_lr=2e-4', '--text_encoder_lr=3e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=3', '--network_dim=128', '--network_alpha=64', '--output_name=train', '--train_batch_size=4', '--save_every_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=1', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--xformers', '--shuffle_caption', '--use_lion_optimizer']' returned non-zero exit status 1.

**Comment by Miloxing** [comment]
昨天运行是正常的，今天报错了，尝试git checkout昨天的版本未解决

**Comment by Akegarasu** [comment]
由于sd-scripts的更新，必须要python 3.10版本。[8abb8645ae40f6f5498770cf554ad2617f660a97](https://github.com/kohya-ss/sd-scripts/commit/8abb8645ae40f6f5498770cf554ad2617f660a97)

**Comment by UltraSoundX** [comment]
> 昨天运行是正常的，今天报错了，尝试git checkout昨天的版本未解决

Colab运行以下代码块切换至python 3.10
`!wget https://github.com/korakot/kora/releases/download/v0.10/py310.sh
!bash ./py310.sh -b -f -p /usr/local
!python -m ipykernel install --name "py310" --user
# 按Ctrl + R重载后执行下面的`
按Ctrl + R重载后即可执行后续代码
