### ISSUE TITLE
ImportError: cannot import name 'builder' from 'google.protobuf.internal'

### ISSUE THREAD

**Issue by Pevernow** [Akegarasu/lora-scripts#250]
训练sdxl报这个错了。。。
07:26:22-457178 INFO     Wrote promopts to file C:\code\lora-scripts\config\autosave\20230929-072622-promopt.txt
07:26:22-460169 INFO     Training started with config file / 训练开始，使用配置文件:
                         C:\code\lora-scripts\config\autosave\20230929-072622.toml
07:26:22-466166 INFO     Task 1165f540-0a7b-4159-a0b4-73debeceb1fd created
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\transformers\utils\import_utils.py", line 1086, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\34503\miniconda3\envs\py310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 22, in <module>
    from ...image_transforms import (
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\transformers\image_transforms.py", line 48, in <module>
    import tensorflow as tf
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\tensorflow\__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\34503\miniconda3\envs\py310\lib\site-packages\google\protobuf\internal\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\diffusers\utils\import_utils.py", line 684, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\34503\miniconda3\envs\py310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 20, in <module>
    from transformers import CLIPImageProcessor, CLIPTextModel, CLIPTokenizer
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\transformers\utils\import_utils.py", line 1077, in __getattr__
    value = getattr(module, name)
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\transformers\utils\import_utils.py", line 1076, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\transformers\utils\import_utils.py", line 1088, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\34503\miniconda3\envs\py310\lib\site-packages\google\protobuf\internal\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\code\lora-scripts\sd-scripts\sdxl_train_network.py", line 3, in <module>
    from library import sdxl_model_util, sdxl_train_util, train_util
  File "C:\code\lora-scripts\sd-scripts\library\sdxl_model_util.py", line 8, in <module>
    from library import model_util
  File "C:\code\lora-scripts\sd-scripts\library\model_util.py", line 9, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler, StableDiffusionPipeline  # , UNet2DConditionModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\diffusers\utils\import_utils.py", line 675, in __getattr__
    value = getattr(module, name)
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\diffusers\utils\import_utils.py", line 675, in __getattr__
    value = getattr(module, name)
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\diffusers\utils\import_utils.py", line 674, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\diffusers\utils\import_utils.py", line 686, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion because of the following error (look up to see its traceback):
Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\34503\miniconda3\envs\py310\lib\site-packages\google\protobuf\internal\__init__.py)
Traceback (most recent call last):
  File "C:\Users\34503\miniconda3\envs\py310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\34503\miniconda3\envs\py310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\accelerate\commands\launch.py", line 996, in <module>
    main()
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\accelerate\commands\launch.py", line 992, in main
    launch_command(args)
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Users\34503\miniconda3\envs\py310\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\34503\\miniconda3\\envs\\py310\\python.exe', './sd-scripts/sdxl_train_network.py', '--config_file', 'C:\\code\\lora-scripts\\config\\autosave\\20230929-072622.toml']' returned non-zero exit status 1.

**Comment by Akegarasu** [comment]
重安环境

**Comment by CharlinChen** [comment]
相同问题，通过pip install protobuf==3.20 解决
P.S.安装的包比较多，就没有完全符合所有包的protobuf版本，不过3.20版本能启动训练

**Comment by leeliangchao** [comment]
> 相同问题，通过pip install protobuf==3.20 解决 P.S.安装的包比较多，就没有完全符合所有包的protobuf版本，不过3.20版本能启动训练

能完全解决问题，我直接在requirements.txt文件中将protobuf改为了==3.20， 添加了tensorboard，tensorboard==tensorboard-2.19.0
