### ISSUE TITLE
用gui訓練SDXL的LoRA，出現這Error，要怎麼做？

### ISSUE THREAD

**Issue by CCJetWing** [Akegarasu/lora-scripts#267]
Error Message:

Traceback (most recent call last):
  File "D:\NEW\lora-scripts\sd-scripts\sdxl_train_network.py", line 176, in <module>
    trainer.train(args)
  File "D:\NEW\lora-scripts\sd-scripts\train_network.py", line 252, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "D:\NEW\lora-scripts\sd-scripts\library\train_util.py", line 1827, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "D:\NEW\lora-scripts\sd-scripts\library\train_util.py", line 876, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.random_crop)
  File "D:\NEW\lora-scripts\sd-scripts\library\train_util.py", line 2170, in cache_batch_latents
    raise RuntimeError(f"NaN detected in latents: {info.absolute_path}")
RuntimeError: NaN detected in latents: D:\scraper\data\LoRA_training\HSEaE20848beF_512_T\10_HSEaE20848beF\beigeshirt_512_00000.png
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\NEW\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 928, in <module>
    main()
  File "D:\NEW\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 924, in main
    launch_command(args)
  File "D:\NEW\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 918, in launch_command
    simple_launcher(args)
  File "D:\NEW\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 580, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\NEW\\lora-scripts\\venv\\Scripts\\python.exe', './sd-scripts/sdxl_train_network.py', '--config_file', 'D:\\NEW\\lora-scripts\\config\\autosave\\20231015-170938.toml']' returned non-zero exit status 1.
17:09:57-932122 ERROR    Training failed / 训练失败

参数预览

model_train_type = "sd-lora"
pretrained_model_name_or_path = "D:/NEW/stable-diffusion-webui/models/Stable-diffusion/epicrealism_naturalSin.safetensors"
v2 = false
train_data_dir = "D:/scraper/data/LoRA_training/HSEaE20848beF_512_T"
prior_loss_weight = 1
resolution = "512,512"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1_024
bucket_reso_steps = 64
output_name = "YYT-HSEaE20848beF_512_v3"
output_dir = "D:/NEW/lora-scripts/output/HSEaE20848beF_512/v3"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 2
max_train_epochs = 20
train_batch_size = 2
gradient_checkpointing = false
network_train_unet_only = false
network_train_text_encoder_only = false
learning_rate = 0.0001
unet_lr = 0.0001
text_encoder_lr = 0.0001
lr_scheduler = "constant"
lr_warmup_steps = 0
optimizer_type = "AdaFactor"
network_module = "networks.lora"
network_dim = 128
network_alpha = 1
network_dropout = 0
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
weighted_captions = false
keep_tokens = 0
max_token_length = 255
seed = 1_337
clip_skip = 2
mixed_precision = "fp16"
full_fp16 = false
full_bf16 = false
xformers = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = false
cache_text_encoder_outputs_to_disk = false
persistent_data_loader_workers = true
optimizer_args = [
  "scale_parameter=False",
  "relative_step=False",
  "warmup_init=False"
]

**Comment by Akegarasu** [comment]
https://github.com/Akegarasu/lora-scripts/issues/207

**Comment by DanielXu123** [comment]
我发现用 mixed_precision = "bf16" 就不会有问题， 'fp16' 就会出这个错

**Comment by lixiang007666** [comment]
mark

**Comment by duanjiding** [comment]
> 题， 'fp16' 就会出这个错

我改成bf16之后发现，bf16只能在A100卡上跑
