### ISSUE TITLE
TypeError: replace_unet_cross_attn_to_xformers.<locals>.forward_xformers() got an unexpected keyword argument 'encoder_hidden_states'

### ISSUE THREAD

**Issue by wcb0402** [Akegarasu/lora-scripts#27]
when train I get the following problem. Have anyone have same problem?

steps:   0%|                                                                           | 0/20880 [00:00<?, ?it/s]epoch 1/20
Traceback (most recent call last):
  File "/data/sd/sd/stable-diffusion-webui/lora-scripts/./sd-scripts/train_network.py", line 642, in <module>
    train(args)
  File "/data/sd/sd/stable-diffusion-webui/lora-scripts/./sd-scripts/train_network.py", line 503, in train
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/data/sd/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/sd/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 489, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/data/sd/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/data/sd/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 582, in forward
    sample, res_samples = downsample_block(
  File "/data/sd/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/sd/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 837, in forward
    hidden_states = attn(
  File "/data/sd/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/sd/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "/data/sd/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/sd/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 291, in forward
    attn_output = self.attn1(
  File "/data/sd/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: replace_unet_cross_attn_to_xformers.<locals>.forward_xformers() got an unexpected keyword argument 'encoder_hidden_states'

**Comment by mendynew** [comment]
install the corresponding version of diffusers

**Comment by h3clikejava** [comment]
> install the corresponding version of diffusers

How to do that?

**Comment by CCDAYY** [comment]
go to venv file and under  windows os go to "Scripts" and under the linux os go to "bin" then python -m pip install diffusers==0.10.0 (many other version are supported you can try different version )

> > install the corresponding version of diffusers
> 
> How to do that?

**Comment by sipie800** [comment]
same here. use diffuser 0.14 till newest all not working

**Comment by Akegarasu** [comment]
try out the newest version
