### ISSUE TITLE
Can't load tokenizer for 'openai/clip-vit-large-patch14'.

### ISSUE THREAD

**Issue by snylonue** [Akegarasu/lora-scripts#270]
Python 3.10.13

```sh
module load cuda/11.8.0 # load cuda environment

source ./venv/bin/activate
./train.sh
```

```
prepare tokenizer
Traceback (most recent call last):
  File "/fsa/home/test11/hoji_lora/lora-scripts/./sd-scripts/train_network.py", line 1009, in <module>
    trainer.train(args)
  File "/fsa/home/test11/hoji_lora/lora-scripts/./sd-scripts/train_network.py", line 144, in train
    tokenizer = self.load_tokenizer(args)
  File "/fsa/home/test11/hoji_lora/lora-scripts/./sd-scripts/train_network.py", line 105, in load_tokenizer
    tokenizer = train_util.load_tokenizer(args)
  File "/fsa/home/test11/hoji_lora/lora-scripts/sd-scripts/library/train_util.py", line 3744, in load_tokenizer
    tokenizer = CLIPTokenizer.from_pretrained(original_path)
  File "/fsa/home/test11/hoji_lora/lora-scripts/venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1809, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Traceback (most recent call last):
  File "/fsa/home/test11/.conda/envs/sd/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/fsa/home/test11/.conda/envs/sd/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/fsa/home/test11/hoji_lora/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 996, in <module>
    main()
  File "/fsa/home/test11/hoji_lora/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 992, in main
    launch_command(args)
  File "/fsa/home/test11/hoji_lora/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/fsa/home/test11/hoji_lora/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/fsa/home/test11/hoji_lora/lora-scripts/venv/bin/python', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=../model/kohakuV4_rev1.safetensors', '--train_data_dir=../dataset', '--output_dir=./output', '--logging_dir=./logs', '--log_prefix=hoji-rev1', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=15', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=hoji-rev1', '--train_batch_size=1', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--clip_skip', '1', '--optimizer_type', 'AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard', '--lowram']' returned non-zero exit status 1.
```

根据 https://github.com/CompVis/stable-diffusion/issues/436 手动下载 `openai/clip-vit-large-patch14` 至 `lora-scripts/huggingface/hub`，报错相同

**Comment by Akegarasu** [comment]
网络问题

**Comment by snylonue** [comment]
> 网络问题

看来是因为机器只有内网（这个报错不太明显
下载` openai/clip-vit-large-patch14`后设置 cache dir 解决

**Comment by chenwei20** [comment]
可以通过修改convert_from_ckpt.py和tokenization_utils_base.py里的相关内容 来解决这个问题.
