### ISSUE TITLE
Linux训练 sdxl1.0 的时候报错：Error while deserializing header: MetadataIncompleteBuffer，请问如何解决？

### ISSUE THREAD

**Issue by soybeanxiaobi** [Akegarasu/lora-scripts#276]
```
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (448, 576), count: 12300
mean ar error (without repeats): 0.02707749766573297
prepare accelerator
loading model for process 0/1
load StableDiffusion checkpoint: ./sd-models/JuggernautXL.safetensors
Traceback (most recent call last):
  File "./sd-scripts/sdxl_train.py", line 753, in <module>
    train(args)
  File "./sd-scripts/sdxl_train.py", line 216, in train
    ) = sdxl_train_util.load_target_model(args, accelerator, "sdxl", weight_dtype)
  File "/sd-scripts/library/sdxl_train_util.py", line 34, in load_target_model
    ) = _load_target_model(
  File "/sd-scripts/library/sdxl_train_util.py", line 75, in _load_target_model
    ) = sdxl_model_util.load_models_from_sdxl_checkpoint(model_version, name_or_path, device, model_dtype)
  File "/sd-scripts/library/sdxl_model_util.py", line 171, in load_models_from_sdxl_checkpoint
    state_dict = load_file(ckpt_path)  # prevent device invalid Error
  File "/opt/conda/lib/python3.10/site-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
14:43:55-288895 ERROR    Training failed / 训练失败  
```

**Comment by soybeanxiaobi** [comment]
https://civitai.com/models/133005/juggernaut-xl

**Comment by soybeanxiaobi** [comment]
使用 sdxl-lora 也不行，提示
```
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (1024, 1024), count: 18
mean ar error (without repeats): 0.0
v_parameterization will be unexpected / SDXL学習ではv_parameterizationは想定外の動作になります
clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: ./sd-models/CopaxTimeLessXLRemote.safetensors
Traceback (most recent call last):
  File "lora-scripts/./sd-scripts/sdxl_train_network.py", line 183, in <module>
    trainer.train(args)
  File "lora-scripts/sd-scripts/train_network.py", line 224, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "lora-scripts/./sd-scripts/sdxl_train_network.py", line 44, in load_target_model
    ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, weight_dtype)
  File "lora-scripts/sd-scripts/library/sdxl_train_util.py", line 34, in load_target_model
    ) = _load_target_model(
  File "lora-scripts/sd-scripts/library/sdxl_train_util.py", line 75, in _load_target_model
    ) = sdxl_model_util.load_models_from_sdxl_checkpoint(model_version, name_or_path, device, model_dtype)
  File "lora-scripts/sd-scripts/library/sdxl_model_util.py", line 171, in load_models_from_sdxl_checkpoint
    state_dict = load_file(ckpt_path)  # prevent device invalid Error
  File "/.pyenv/versions/3.10.8/lib/python3.10/site-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
10:39:38-052005 ERROR    CompletedProcess(args=['/.pyenv/versions/3.10.8/bin/python', '-m', 
                         'accelerate.commands.launch', '--num_cpu_threads_per_process', '2', '--quiet',    
                         './sd-scripts/sdxl_train_network.py', '--config_file',                            
                         'lora-scripts/config/autosave/202
                         31103-103932.toml'], returncode=1)                                                
10:39:38-054049 ERROR    Training failed / 训练失败
```

**Comment by soybeanxiaobi** [comment]
```
load_models_from_sdxl_checkpoint model_version sdxl_base_v1-0
load_models_from_sdxl_checkpoint ckpt_path ./sd-models/JuggernautXL.safetensors
load_models_from_sdxl_checkpoint map_location cpu
load_models_from_sdxl_checkpoint model_util.is_safetensors(ckpt_path) True
```

**Comment by Akegarasu** [comment]
模型损坏

**Comment by soybeanxiaobi** [comment]
换了4、5个xl模型，从https://civitai.com/下载了好几个模型都不行。用了一个在运行的xl模型进行训练还是不行诶。 @Akegarasu 
比如：https://civitai.com/models/133005/juggernaut-xl

**Comment by soybeanxiaobi** [comment]
> 模型损坏

请问你使用 webui 有遇到过这个问题嘛？比如这个模型：
https://civitai.com/models/133005/juggernaut-xl

**Comment by soybeanxiaobi** [comment]
和这个会有关系吗？ `load_models_from_sdxl_checkpoint map_location cpu`

**Comment by soybeanxiaobi** [comment]
```
Linux Python 3.10.11 /opt/conda/bin/python             
INFO     Torch 2.0.1                                            
Torch backend: nVidia CUDA 11.7 cuDNN 8500             
Torch detected GPU: NVIDIA A100 80GB PCIe VRAM 81085
```
