### ISSUE TITLE
更新到V1.7.5后dreambooth学习率有BUG，

### ISSUE THREAD

**Issue by poxiao0411** [Akegarasu/lora-scripts#281]
override steps. steps for 200 epochs is / 指定エポックまでのステップ数: 62400
Traceback (most recent call last):
  File "F:\BaiduNetdiskDownload\lora_training\lora-scripts-v1.5.1\sd-scripts\train_db.py", line 500, in <module>
    train(args)
  File "F:\BaiduNetdiskDownload\lora_training\lora-scripts-v1.5.1\sd-scripts\train_db.py", line 209, in train
    lr_scheduler = train_util.get_scheduler_fix(args, optimizer, accelerator.num_processes)
  File "F:\BaiduNetdiskDownload\lora_training\lora-scripts-v1.5.1\sd-scripts\library\train_util.py", line 3708, in get_scheduler_fix
    return schedule_func(
  File "F:\BaiduNetdiskDownload\lora_training\lora-scripts-v1.5.1\python\lib\site-packages\diffusers\optimization.py", line 218, in get_cosine_with_hard_restarts_schedule_with_warmup
    return LambdaLR(optimizer, lr_lambda, last_epoch)
  File "F:\BaiduNetdiskDownload\lora_training\lora-scripts-v1.5.1\python\lib\site-packages\torch\optim\lr_scheduler.py", line 221, in __init__
    super().__init__(optimizer, last_epoch, verbose)
  File "F:\BaiduNetdiskDownload\lora_training\lora-scripts-v1.5.1\python\lib\site-packages\torch\optim\lr_scheduler.py", line 79, in __init__
    self._initial_step()
  File "F:\BaiduNetdiskDownload\lora_training\lora-scripts-v1.5.1\python\lib\site-packages\torch\optim\lr_scheduler.py", line 85, in _initial_step
    self.step()
  File "F:\BaiduNetdiskDownload\lora_training\lora-scripts-v1.5.1\python\lib\site-packages\torch\optim\lr_scheduler.py", line 150, in step
    values = self.get_lr()
  File "F:\BaiduNetdiskDownload\lora_training\lora-scripts-v1.5.1\python\lib\site-packages\torch\optim\lr_scheduler.py", line 268, in get_lr
    return [base_lr * lmbda(self.last_epoch)
  File "F:\BaiduNetdiskDownload\lora_training\lora-scripts-v1.5.1\python\lib\site-packages\torch\optim\lr_scheduler.py", line 268, in <listcomp>
    return [base_lr * lmbda(self.last_epoch)
TypeError: can't multiply sequence by non-int of type 'float'
17:12:49-473060 ERROR    Training failed / 训练失败

使用constant可以接着跑！！！！！！！！！但到训练步数的时候，还是会崩

  File "F:\BaiduNetdiskDownload\lora_training\lora-scripts-v1.5.1\python\lib\site-packages\bitsandbytes\functional.py", line 1312, in optimizer_update_8bit_blockwise
    ct.c_float(lr),
TypeError: must be real number, not str
steps:   0%|                                                                                 | 0/62400 [00:38<?, ?it/s]
17:17:07-295460 ERROR    Training failed / 训练失败

**Comment by Akegarasu** [comment]
已修复
