### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [4, 56, 48] at entry 0 and [4, 48, 48] at entry 5

### ISSUE THREAD

**Issue by jxhxgt** [Akegarasu/lora-scripts#282]

**Comment by jxhxgt** [comment]
raceback (most recent call last):
  File "E:\lora-scripts\sd-scripts\train_db.py", line 491, in <module>
    train(args)
  File "E:\lora-scripts\sd-scripts\train_db.py", line 280, in train
    for step, batch in enumerate(train_dataloader):
  File "E:\lora-scripts\venv\lib\site-packages\accelerate\data_loader.py", line 394, in __iter__
    next_batch = next(dataloader_iter)
  File "E:\lora-scripts\venv\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "E:\lora-scripts\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "E:\lora-scripts\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "E:\lora-scripts\venv\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "E:\lora-scripts\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "E:\lora-scripts\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\lora-scripts\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\lora-scripts\venv\lib\site-packages\torch\utils\data\dataset.py", line 243, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "E:\lora-scripts\sd-scripts\library\train_util.py", line 1231, in __getitem__
    example["latents"] = torch.stack(latents_list) if latents_list[0] is not None else None
RuntimeError: stack expects each tensor to be equal size, but got [4, 56, 48] at entry 0 and [4, 48, 48] at entry 5

steps:   4%|██▏                                                    | 2379/61140 [33:38<13:50:59,  1.18it/s, loss=0.128]
Traceback (most recent call last):
  File "C:\Users\hjx43\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\hjx43\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\lora-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\lora-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "E:\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\lora-scripts\\venv\\Scripts\\python.exe', './sd-scripts/train_db.py', '--pretrained_model_name_or_path=E:\\sd-webui-aki\\sd-webui-aki-v4.2\\models\\Stable-diffusion\\ACertainThing-half.ckpt', '--output_dir=./output', '--logging_dir=./logs', '--resolution=320,576', '--max_train_epochs=20', '--learning_rate=5e-6', '--lr_scheduler=constant_with_warmup', '--output_name=db', '--train_batch_size=8', '--save_every_n_epochs=5', '--save_precision=bf16', '--seed=1026', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--vae_batch_size=4', '--xformers', '--train_data_dir=E:\\xlzl\\tupian\\jpg', '--clip_skip=2', '--persistent_data_loader_workers', '--shuffle_caption', '--weighted_captions', '--cache_latents', '--cache_latents_to_disk', '--gradient_checkpointing', '--noise_offset=0.0375', '--adaptive_noise_scale=0.0375', '--optimizer_type=PagedAdamW8bit', '--optimizer_args', 'weight_decay=0.01', '--reg_data_dir=E:\\DAIXUNLIAN1\\reg', '--keep_tokens=3', '--min_snr_gamma=5', '--lr_scheduler_num_cycles=1', '--enable_bucket', '--min_bucket_reso=128', '--max_bucket_reso=896', '--full_bf16', '--mixed_precision=bf16', '--lr_warmup_steps=50', '--caption_dropout_rate=0.1', '--caption_tag_dropout_rate=0.1']' returned non-zero exit status 1.
Train finished

**Comment by Akegarasu** [comment]
https://github.com/kohya-ss/sd-scripts/issues/522
