### ISSUE TITLE
Train with RuntimeError

### ISSUE THREAD

**Issue by TheSlientnight** [Akegarasu/lora-scripts#29]
My graphics card is RTX 2080, when I run train.ps1 with ckpt model I got this problem:
    RuntimeError: PytorchStreamReader failed reading zip archive: failed central directory
My CUAD version is 11.7, is that torch version's problem? And when I changed model to safetensors, I got a new problem:
    KeyError:'encoder.conv_in.weight'
How can I fix it, appreciate a lot

**Comment by TheSlientnight** [comment]
[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 137.65it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 640), count: 102
mean ar error (without repeats): 0.0
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
loading u-net: <All keys matched successfully>
Traceback (most recent call last):
  File "D:\lora_train\sd-scripts\train_network.py", line 642, in <module>
    train(args)
  File "D:\lora_train\sd-scripts\train_network.py", line 114, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "D:\lora_train\sd-scripts\library\train_util.py", line 2008, in load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path)
  File "D:\lora_train\sd-scripts\library\model_util.py", line 885, in load_models_from_stable_diffusion_checkpoint
    converted_vae_checkpoint = convert_ldm_vae_checkpoint(state_dict, vae_config)
  File "D:\lora_train\sd-scripts\library\model_util.py", line 398, in convert_ldm_vae_checkpoint
    new_checkpoint["encoder.conv_in.weight"] = vae_state_dict["encoder.conv_in.weight"]
KeyError: 'encoder.conv_in.weight'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\lora_train\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\lora_train\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\lora_train\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\lora_train\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\lora_train\\venv\\Scripts\\python.exe', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=./sd-models/def.safetensors', '--train_data_dir=./train/sweetGril', '--output_dir=./output', '--logging_dir=./logs', '--resolution=512,640', '--network_module=networks.lora', '--max_train_epochs=15', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=sweet_gril', '--train_batch_size=1', '--save_every_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--xformers', '--shuffle_caption', '--use_8bit_adam']' returned non-zero exit status 1.
Train finished

**Comment by Akegarasu** [comment]
check your vae model.

**Comment by TheSlientnight** [comment]
> 

diffusers version is 0.10.2, shoud I upgrade it?

**Comment by TheSlientnight** [comment]
> check your vae model.

how can I know what kind vae model I've got...
is that mean checkpoint model have some problem?

**Comment by Akegarasu** [comment]
I don't think you need to upgrade diffusers. Check your checkpoint (vae inside it). Maybe you could try to bake in a normal vae into checkpoint to fix this problem.
