### ISSUE TITLE
v1.8.0 (332c558) tag编辑器无法加载

### ISSUE THREAD

**Issue by 1MSD-NVA** [Akegarasu/lora-scripts#293]
运行启动脚本后之后遇到如下报错，tag编辑器无法加载：
Traceback (most recent call last):
  File "\lora-scripts-v1.5.0\mikazuki\dataset-tag-editor\scripts\launch.py", line 101, in <module>
    import interface
  File "\lora-scripts-v1.5.0\mikazuki\dataset-tag-editor\scripts\interface.py", line 12, in <module>
    import gradio as gr
  File "\lora-scripts-v1.5.0\python\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "\lora-scripts-v1.5.0\python\lib\site-packages\gradio\components.py", line 55, in <module>
    from gradio import processing_utils, utils
  File "\lora-scripts-v1.5.0\python\lib\site-packages\gradio\processing_utils.py", line 20, in <module>
    from pydub import AudioSegment
  File "\lora-scripts-v1.5.0\python\lib\site-packages\pydub\__init__.py", line 1, in <module>
    from .audio_segment import AudioSegment
  File "\lora-scripts-v1.5.0\python\lib\site-packages\pydub\audio_segment.py", line 152, in <module>
    class AudioSegment(object):
  File "\lora-scripts-v1.5.0\python\lib\site-packages\pydub\audio_segment.py", line 163, in AudioSegment
    converter = get_encoder_name()  # either ffmpeg or avconv
  File "\lora-scripts-v1.5.0\python\lib\site-packages\pydub\utils.py", line 164, in get_encoder_name
    if which("avconv"):
  File "\lora-scripts-v1.5.0\python\lib\site-packages\pydub\utils.py", line 152, in which
    envdir_list = [os.curdir] + os.environ["PATH"].split(os.pathsep)
  File "\lora-scripts-v1.5.0\python\lib\os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'PATH'

起初以为是环境变量问题，但是将训练器的python根目录加入系统的PATH后仍然报错

**Comment by 1MSD-NVA** [comment]
32f981c仍未解决此bug，是安装问题吗

**Comment by 1MSD-NVA** [comment]
@Akegarasu 
根据copilot提示试着把32f981c的gui.py第54行改为
` os.environ.setdefault("PATH", "%VIRTUAL_ENV%\Scripts;%PATH%") `
后可以在训练UI正常运行tag编辑器，但是这应该是添加整个系统的PATH进去，我的机器PATH里有另一个python所以能够运行，路径改成训练器自带的python应该更优。
