### ISSUE TITLE
OSError: openai/clip-vit-large-patch14

### ISSUE THREAD

**Issue by caisl1** [Akegarasu/lora-scripts#299]
Traceback (most recent call last):
  File "/app/lora-scripts/./sd-scripts/train_network.py", line 1012, in <module>
    trainer.train(args)
  File "/app/lora-scripts/./sd-scripts/train_network.py", line 148, in train
    tokenizer = self.load_tokenizer(args)
  File "/app/lora-scripts/./sd-scripts/train_network.py", line 106, in load_tokenizer
    tokenizer = train_util.load_tokenizer(args)
  File "/app/lora-scripts/sd-scripts/library/train_util.py", line 3772, in load_tokenizer
    tokenizer = CLIPTokenizer.from_pretrained(original_path)
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1809, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

How to solve it?

**Comment by Akegarasu** [comment]
check your network connection to huggingface. delete cache

**Comment by caisl1** [comment]
邮件已收到，谢谢！

**Comment by babyta** [comment]
train_utils.py 文件这里写死  def load_tokenizer(args: argparse.Namespace):
    print("prepare tokenizer")
    original_path = V2_STABLE_DIFFUSION_PATH if args.v2 else TOKENIZER_PATH
我用的本地文件，例如：original_path = '/home/xxxxx/xxxxx/openai/clip-vit-large-patch14'

**Comment by ZhianLin** [comment]
自己部署autodl的云端，那就在/root/lora-scripts/huggingface/hub/删掉文件夹models--openai--clip-vit-large-patch14，然后开启学术加速，然后在终端而不是在Notebook里面运行。

**Comment by caisl1** [comment]
邮件已收到，谢谢！
