### ISSUE TITLE
运行train.sh失败

### ISSUE THREAD

**Issue by duskNNNN** [Akegarasu/lora-scripts#30]
> run `train.sh` info

```shell
(venv) taper@pc:~/App/lora-scripts$ ./train.sh 
Traceback (most recent call last):
  File "/home/taper/App/python/3.10.6/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/taper/App/python/3.10.6/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/taper/App/python/3.10.6/lib/python3.10/site-packages/accelerate/commands/launch.py", line 747, in launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/taper/App/python/3.10.6/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 64, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/home/taper/App/python/3.10.6/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 117, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'command_file'
```
> `train.sh`
```shell
# 我只修改了这几行
pretrained_model="./sd-models/v1-5-pruned-emaonly.safetensors" # base model path | 底模路径
train_data_dir="./train/xxx/"              # train dataset path | 训练数据集路径
resolution="512,640"      # image resolution w,h. 图片分辨率，宽,高。支持非正方形，但必须是 64 倍数。
max_train_epoches=20      # max train epoches | 最大训练 epoch
output_name="xxx"           # output model name | 模型保存名称
```
麻烦作者大大看看到底是哪里出问题了，这个`accelerate`的错误信息实在不好排查

**Comment by duskNNNN** [comment]
今早重新拉取后已解决，非常感谢大佬的付出

**Comment by tuoyuxiang** [comment]
> 今早重新拉取后已解决，非常感谢大佬的付出

遇到了同样的问题，请问怎么解决的？
