### ISSUE TITLE
使用Train Tools训练Lora时，跳epoch，并且有警告。

### ISSUE THREAD

**Issue by volpe0130** [Akegarasu/lora-scripts#315]
当我尝试训练epoch，出现了gradio报错，显示类中缺少box组件错误。
“*** Error completing request
*** Arguments: ('task(010rdflp1qx7ocu)', 'RadyWolf_furry_v0.01', None, 'himawarimix_v100.safetensors [1c3b884d1d]', 1.0, 5.0, 2.0, True, ['AdamW8bit'], '0.0001', 128.0, 64.0, 2.0, 'bf16', True, False, False, 'best quality,Amazing,finely detail,extremely detailed CG unity 8k wallpaper,fur,fursuit,kemono', 'low quality', ['DPM++ 2M SDE Exponential'], '28', 768, 768, 1, 1, '10', '-1', '0.6,0.7,0.8,1') {}
    Traceback (most recent call last):
      File "E:\BaiduNetdiskDownload\秋葉整合包\sd-webui-aki-v4.5\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "E:\BaiduNetdiskDownload\秋葉整合包\sd-webui-aki-v4.5\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "E:\BaiduNetdiskDownload\秋葉整合包\sd-webui-aki-v4.5\extensions\sd-webui-train-tools\liasece_sd_webui_train_tools\train_ui.py", line 109, in on_train_begin_click
        cfg.change_output_name = project+r"-"+version
    TypeError: can only concatenate str (not "NoneType") to str

---
Traceback (most recent call last):
  File "E:\BaiduNetdiskDownload\秋葉整合包\sd-webui-aki-v4.5\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\BaiduNetdiskDownload\秋葉整合包\sd-webui-aki-v4.5\python\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\BaiduNetdiskDownload\秋葉整合包\sd-webui-aki-v4.5\python\lib\site-packages\gradio\blocks.py", line 1332, in postprocess_data
    assert isinstance(
AssertionError: <class 'gradio.layouts.Box'> Component with id 4446 not a valid output component.”
   之后我自行下载了新的gradio库修复，虽然可以进行训练了。但是出现了跳epoch的情况。当我训练5个epoch时，第1，第3个epoch被奇怪的跳过了。 如图片所示：
![QQ图片20231225160419](https://github.com/Akegarasu/lora-scripts/assets/147473105/10a8a4f7-b3f1-4491-9777-35b272482fc1)
    当我更新完后，再次出现gradio的class 'gradio.layouts.Box'错误。

**Comment by Akegarasu** [comment]
这不是我的
