### ISSUE TITLE
AutoDL镜像故障

### ISSUE THREAD

**Issue by pynooblin** [Akegarasu/lora-scripts#320]
镜像名称：Akegarasu/lora-scripts/lora-train
版本号：v1.7.2
已手动更新至 SD-Trainer v1.8.2
科学加速开启。
报错：
Loading settings from /root/lora-scripts/config/autosave/20240103-182931.toml...
/root/lora-scripts/config/autosave/20240103-182931
prepare tokenizer
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/vocab.json (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:980: The handshake operation timed out')))' thrown while requesting HEAD https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/vocab.json
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/root/miniconda3/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:980: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/vocab.json (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:980: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/lora-scripts/./sd-scripts/train_network.py", line 996, in <module>
    trainer.train(args)
  File "/root/lora-scripts/./sd-scripts/train_network.py", line 154, in train
    tokenizer = self.load_tokenizer(args)
  File "/root/lora-scripts/./sd-scripts/train_network.py", line 107, in load_tokenizer
    tokenizer = train_util.load_tokenizer(args)
  File "/root/lora-scripts/sd-scripts/library/train_util.py", line 3833, in load_tokenizer
    tokenizer = CLIPTokenizer.from_pretrained(original_path)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1784, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1195, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1532, in get_hf_file_metadata
    r = _request_wrapper(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 407, in _request_wrapper
    response = _request_wrapper(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 442, in _request_wrapper
    return http_backoff(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 228, in http_backoff
    raise err
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 212, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/vocab.json (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:980: The handshake operation timed out')))
18:29:46-818240 ERROR    Training failed / 训练失败           

请问如何解决？

**Comment by pynooblin** [comment]
已自行解决

**Comment by obzkevea** [comment]
同，怎么解决的兄弟

**Comment by pynooblin** [comment]
> 同，怎么解决的兄弟

自行拷贝Huggingface模型库到本地（云端本地），修改相关联的调用模型header指向本地存储地址。
好处是能跳过tokenizer试图建立远程连接的环节，启动速度加倍；缺点是要自己保存镜像，再次拉取时巨慢

**Comment by obzkevea** [comment]
> > 同，怎么解决的兄弟
> 
> 自行拷贝Huggingface模型库到本地（云端本地），修改相关联的调用模型header指向本地存储地址。 好处是能跳过tokenizer试图建立远程连接的环节，启动速度加倍；缺点是要自己保存镜像，再次拉取时巨慢

谢谢，后来发现重置镜像后不用gitpull更新就不会出现这个bug了，云平台上
