### ISSUE TITLE
1.8.3双卡训练报错

### ISSUE THREAD

**Issue by yisaaier** [Akegarasu/lora-scripts#328]
NOTE: Redirects are currently not supported in Windows or MacOs.
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-S3F14MD]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-S3F14MD]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
Loading settings from D:\ai\lora-scripts-v1.5.1\config\autosave\20240111-153332.toml...
D:\ai\lora-scripts-v1.5.1\config\autosave\20240111-153332
Loading settings from D:\ai\lora-scripts-v1.5.1\config\autosave\20240111-153332.toml...
D:\ai\lora-scripts-v1.5.1\config\autosave\20240111-153332
prepare tokenizer
prepare tokenizer
update token length: 255
update token length: 255
Using DreamBooth method.Using DreamBooth method.

prepare images.
found directory D:\ai\shu_cahi\测试\5_1263 contains 321 image files
1605 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 8
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1920
  bucket_reso_steps: 64
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "D:\ai\shu_cahi\测试\5_1263"
    image_count: 321
    num_repeats: 5
    shuffle_caption: True
    keep_tokens: 1
    keep_tokens_separator:
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: 1263
    caption_extension: .txt

[Dataset 0]
loading image sizes.
  0%|                                                                                          | 0/321 [00:00<?, ?it/s]prepare images.
100%|██████████████████████████████████████████████████████████████████████████████| 321/321 [00:00<00:00, 2999.90it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 640), count: 290
bucket 1: resolution (448, 576), count: 1145
bucket 2: resolution (512, 512), count: 60
bucket 3: resolution (576, 448), count: 105
bucket 4: resolution (640, 384), count: 5
mean ar error (without repeats): 0.037451980772725074
preparing accelerator
found directory D:\ai\shu_cahi\测试\5_1263 contains 321 image files
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-S3F14MD]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-S3F14MD]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
Traceback (most recent call last):
  File "D:\ai\lora-scripts-v1.5.1\sd-scripts\train_network.py", line 996, in <module>
    trainer.train(args)
  File "D:\ai\lora-scripts-v1.5.1\sd-scripts\train_network.py", line 226, in train
    accelerator = train_util.prepare_accelerator(args)
  File "D:\ai\lora-scripts-v1.5.1\sd-scripts\library\train_util.py", line 3896, in prepare_accelerator
    accelerator = Accelerator(
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\accelerate\accelerator.py", line 371, in __init__
    self.state = AcceleratorState(
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\accelerate\state.py", line 758, in __init__
    PartialState(cpu, **kwargs)
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\accelerate\state.py", line 217, in __init__
    torch.distributed.init_process_group(backend=self.backend, **kwargs)
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\torch\distributed\distributed_c10d.py", line 895, in init_process_group
    default_pg = _new_process_group_helper(
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\torch\distributed\distributed_c10d.py", line 998, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
1605 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 8
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1920
  bucket_reso_steps: 64
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "D:\ai\shu_cahi\测试\5_1263"
    image_count: 321
    num_repeats: 5
    shuffle_caption: True
    keep_tokens: 1
    keep_tokens_separator:
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: 1263
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████████████████████████| 321/321 [00:00<00:00, 2696.59it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 640), count: 290
bucket 1: resolution (448, 576), count: 1145
bucket 2: resolution (512, 512), count: 60
bucket 3: resolution (576, 448), count: 105
bucket 4: resolution (640, 384), count: 5
mean ar error (without repeats): 0.037451980772725074
preparing accelerator
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-S3F14MD]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-S3F14MD]:29500 (system error: 10049 - 在其上下文中，该请求的地址无效。).
Traceback (most recent call last):
  File "D:\ai\lora-scripts-v1.5.1\sd-scripts\train_network.py", line 996, in <module>
    trainer.train(args)
  File "D:\ai\lora-scripts-v1.5.1\sd-scripts\train_network.py", line 226, in train
    accelerator = train_util.prepare_accelerator(args)
  File "D:\ai\lora-scripts-v1.5.1\sd-scripts\library\train_util.py", line 3896, in prepare_accelerator
    accelerator = Accelerator(
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\accelerate\accelerator.py", line 371, in __init__
    self.state = AcceleratorState(
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\accelerate\state.py", line 758, in __init__
    PartialState(cpu, **kwargs)
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\accelerate\state.py", line 217, in __init__
    torch.distributed.init_process_group(backend=self.backend, **kwargs)
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\torch\distributed\distributed_c10d.py", line 895, in init_process_group
    default_pg = _new_process_group_helper(
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\torch\distributed\distributed_c10d.py", line 998, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 25488) of binary: D:\ai\lora-scripts-v1.5.1\python\python.exe
Traceback (most recent call last):
  File "D:\ai\lora-scripts-v1.5.1\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ai\lora-scripts-v1.5.1\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\accelerate\commands\launch.py", line 1027, in <module>
    main()
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\accelerate\commands\launch.py", line 1023, in main
    launch_command(args)
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\accelerate\commands\launch.py", line 1008, in launch_command
    multi_gpu_launcher(args)
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\accelerate\commands\launch.py", line 666, in multi_gpu_launcher
    distrib_run.run(args)
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\torch\distributed\run.py", line 785, in run
    elastic_launch(
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\ai\lora-scripts-v1.5.1\python\lib\site-packages\torch\distributed\launcher\api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
./sd-scripts/train_network.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-01-11_15:34:09
  host      : DESKTOP-S3F14MD
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 24080)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-11_15:34:09
  host      : DESKTOP-S3F14MD
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 25488)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
15:34:26-065458 ERROR    Training failed / 训练失败

**Comment by Akegarasu** [comment]
https://github.com/Akegarasu/lora-scripts/issues/308
