### ISSUE TITLE
mac m2 support

### ISSUE THREAD

**Issue by gushenjie** [Akegarasu/lora-scripts#360]
![Uploading image.png…]()

**Comment by gushenjie** [comment]
09:52:18-855432 ERROR    Torch is not able to use GPU, please check your torch installation.                                   
                          Use --skip-prepare-environment to disable this check                                                 
09:52:18-856080 ERROR    ！！！Torch 无法使用 GPU，您无法正常开始训练！！！                                                    
                         您的显卡可能并不支持，或是 torch 安装有误。请检查您的 torch 安装。                                    
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorboard/main.py", line 53, in <module>
    run_main()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorboard/main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorboard/program.py", line 276, in main
    return runner(self.flags) or 0
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorboard/program.py", line 292, in _run_serve_subcommand
    server = self._make_server()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorboard/program.py", line 467, in _make_server
    app = application.TensorBoardWSGIApp(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorboard/backend/application.py", line 140, in TensorBoardWSGIApp
    return TensorBoardWSGI(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorboard/backend/application.py", line 253, in __init__
    raise ValueError(
ValueError: Duplicate plugins for name projector
