### ISSUE TITLE
Ubuntu+cuda11+troch2.2.1 训练失败

### ISSUE THREAD

**Issue by LTtt456c** [Akegarasu/lora-scripts#368]
TensorBoard 2.10.1 at http://127.0.0.1:6006/ (Press CTRL+C to quit)
11:40:08-832595 INFO     Torch 2.2.0+cu118
11:40:09-061717 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
11:40:09-136322 INFO     Torch detected GPU: NVIDIA A100-SXM4-80GB VRAM 40950 Arch (8, 0) Cores 108
11:40:55-039352 INFO     Training started with config file / 训练开始，使用配置文件:
                         /root/lora/lora-scripts/config/autosave/20240303-114055.toml
11:40:55-040973 INFO     Task 249b593f-83c8-4281-9ac4-fecced72f486 created
Traceback (most recent call last):
  File "/root/lora/lora-scripts/./sd-scripts/train_network.py", line 30, in <module>
    import library.train_util as train_util
  File "/root/lora/lora-scripts/sd-scripts/library/train_util.py", line 37, in <module>
    from torchvision import transforms
  File "/root/.conda/envs/sd/lib/python3.10/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/root/.conda/envs/sd/lib/python3.10/site-packages/torchvision/_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/root/.conda/envs/sd/lib/python3.10/site-packages/torch/library.py", line 440, in inner
    handle = entry.abstract_impl.register(func_to_register, source)
  File "/root/.conda/envs/sd/lib/python3.10/site-packages/torch/_library/abstract_impl.py", line 30, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist
11:41:07-339489 ERROR    Training failed / 训练失败

**Comment by LTtt456c** [comment]
解决了 模型路径问题 使用绝对路径程序找不到...... Linux下只能用 ./sd-models/xxx.safetensors 模型

**Comment by LTtt456c** [comment]
解决了 模型路径问题 使用绝对路径程序找不到...... Linux下只能用 ./sd-models/xxx.safetensors 模型

**Comment by RazgrizHsu** [comment]
我也遇到一樣的問題，確定路徑的確沒問題，但還是出現這個
`RuntimeError: operator torchvision::nms does not exist`

請問我能從哪裡進行檢查，謝謝
