### ISSUE TITLE
ubuntu系统下安装了两个3090显卡 但是报错

### ISSUE THREAD

**Issue by ryouxin** [Akegarasu/lora-scripts#37]
Traceback (most recent call last):
  File "/home/ipfs10/lora/lora-scripts/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ipfs10/lora/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/ipfs10/lora/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/home/ipfs10/lora/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ipfs10/lora/lora-scripts/venv/bin/python3', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=/home/ipfs10/stable-diffusion-webui/models/Stable-diffusion/yy/yy_900.safetensors', '--train_data_dir=./train/sucai', '--output_dir=./output', '--logging_dir=./logs', '--resolution=512,640', '--network_module=networks.lora', '--max_train_epochs=10', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=64', '--network_alpha=32', '--output_name=aki', '--train_batch_size=1', '--save_every_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--use_8bit_adam', '--noise_offset', '0']' returned non-zero exit status 1.

**Comment by ryouxin** [comment]
![image](https://user-images.githubusercontent.com/6713847/225201068-14d63b3a-bfc7-4d96-8105-75ae57a9329d.png)
明确感觉到他在使用显存 但是还是会爆掉

**Comment by ryouxin** [comment]
![image](https://user-images.githubusercontent.com/6713847/225201198-9da679d0-9dd3-4ba6-a92a-34e873b015b3.png)
这是我的配置

**Comment by ryouxin** [comment]
已解决
