### ISSUE TITLE
继续训练失败

### ISSUE THREAD

**Issue by wzgrx** [Akegarasu/lora-scripts#389]
Traceback (most recent call last):
  File "G:\Soft\lora-scripts\sd-scripts\train_network.py", line 1063, in <module>
    trainer.train(args)
  File "G:\Soft\lora-scripts\sd-scripts\train_network.py", line 460, in train
    train_util.resume_from_local_or_hf_if_specified(accelerator, args)
  File "G:\Soft\lora-scripts\sd-scripts\library\train_util.py", line 3571, in resume_from_local_or_hf_if_specified
    accelerator.load_state(args.resume)
  File "G:\Soft\lora-scripts\venv\lib\site-packages\accelerate\accelerator.py", line 2790, in load_state
    raise ValueError(f"Tried to find {input_dir} but folder does not exist")
ValueError: Tried to find G:/Soft/lora-scripts/output/ag-000001.safetensors but folder does not exist
12:08:38-055960 ERROR    Training failed / 训练失败

**Comment by kurolykin** [comment]
怎么解决的

**Comment by qetuoadgjlzcb** [comment]
我也遇到了同样的问题，请问是怎么解决的？

**Comment by kslz** [comment]
> 我也遇到了同样的问题，请问是怎么解决的？

这里应该指向一个路径而不是具体的模型文件
