### ISSUE TITLE
vevn中已经安装了xformers，启用后开始训练，报错说没有这个包

### ISSUE THREAD

**Issue by yatoubusha** [Akegarasu/lora-scripts#409]
raceback (most recent call last):
  File "/root/lora-scripts-main/sd-scripts/library/train_util.py", line 2579, in replace_unet_modules
Traceback (most recent call last):
  File "/root/lora-scripts-main/sd-scripts/library/train_util.py", line 2579, in replace_unet_modules
    import xformers.ops
ModuleNotFoundError: No module named 'xformers'

**Comment by wTechArtist** [comment]
请问解决了嘛，同样遇到了这个报错
