### ISSUE TITLE
阿里云环境启动报错,提示缺少库tkinter

### ISSUE THREAD

**Issue by magictext** [Akegarasu/lora-scripts#447]
```
root@dsw-394403-86d7654dd8-8588r:/mnt/workspace/lora-scripts# bash run_gui.sh
23:57:45-406252 INFO     Starting SD-Trainer Mikazuki GUI...                                                                                                                                                                     
23:57:45-409138 INFO     Base directory: /mnt/workspace/lora-scripts, Working directory: /mnt/workspace/lora-scripts                                                                                                             
23:57:45-409888 INFO     Linux Python 3.10.12 /usr/bin/python                                                                                                                                                                    
23:57:45-412938 INFO     Starting tageditor...                                                                                                                                                                                   
23:57:45-413856 INFO     Starting tensorboard...                                                                                                                                                                                 
23:57:45-458500 INFO     Server started at http://127.0.0.1:28000                                                                                                                                                                
Traceback (most recent call last):
  File "/mnt/workspace/lora-scripts/gui.py", line 82, in <module>
    launch()
  File "/mnt/workspace/lora-scripts/gui.py", line 77, in launch
    uvicorn.run("mikazuki.app:app", host=args.host, port=args.port, log_level="error")
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/workspace/lora-scripts/mikazuki/app/__init__.py", line 1, in <module>
    from . import application
  File "/mnt/workspace/lora-scripts/mikazuki/app/application.py", line 14, in <module>
    from mikazuki.app.api import load_schemas
  File "/mnt/workspace/lora-scripts/mikazuki/app/api.py", line 22, in <module>
    from mikazuki.utils.tk_window import (open_directory_selector,
  File "/mnt/workspace/lora-scripts/mikazuki/utils/tk_window.py", line 1, in <module>
    import tkinter
ModuleNotFoundError: No module named 'tkinter'
root@dsw-394403-86d7654dd8-8588r:/mnt/workspace/lora-scripts# TensorFlow installation not found - running with reduced feature set.

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

TensorBoard 2.10.1 at http://127.0.0.1:6006/ (Press CTRL+C to quit)
```

提示缺少库tkinter，然而这个库应该是标准库，是阿里云提供的环节有问题吗

**Comment by yk-svg** [comment]
我遇到了和您类似的问题，但问题是dsw上好像无法图形化
问题：
TclError: no display name and no $DISPLAY environment variable
---------------------------------------------------------------------------
TclError                                  Traceback (most recent call last)
Cell In[2], line 3
      1 # Tkinter
      2 import tkinter
----> 3 win=tkinter.Tk()
      4 win.title("我的第一个GUI程序")
      5 win.mainloop()    # 进入消息循环，也就是显示窗口

File /usr/local/lib/python3.10/tkinter/__init__.py:2299, in Tk.__init__(self, screenName, baseName, className, useTk, sync, use)
   2297         baseName = baseName + ext
   2298 interactive = False
-> 2299 self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
   2300 if useTk:
   2301     self._loadtk()

TclError: no display name and no $DISPLAY environment variable
