### ISSUE TITLE
TypeError: AdamW8bit.__init__() got an unexpected keyword argument 'decouple'

### ISSUE THREAD

**Issue by zhouheqin** [Akegarasu/lora-scripts#467]
Traceback (most recent call last):
  File "E:\lora trainer\lora-scripts-v1.8.5\sd-scripts\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "E:\lora trainer\lora-scripts-v1.8.5\sd-scripts\train_network.py", line 367, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "E:\lora trainer\lora-scripts-v1.8.5\sd-scripts\library\train_util.py", line 4066, in get_optimizer
    optimizer = optimizer_class(trainable_params, lr=lr, **optimizer_kwargs)
TypeError: AdamW8bit.__init__() got an unexpected keyword argument 'decouple'
12:32:08-948920 ERROR    Training failed / 训练失败

这是为啥，大佬有解决办法吗？

**Comment by Akegarasu** [comment]
update
