### ISSUE TITLE
梯度检查错误 显存爆炸 RuntimeError: only Tensors of floating point dtype can require gradients

### ISSUE THREAD

**Issue by whmc76** [Akegarasu/lora-scripts#482]
2024-08-24 01:24:53 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:668
2024-08-24 01:24:53 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:668
2024-08-24 01:24:53 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:668
2024-08-24 01:24:53 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:668
2024-08-24 01:24:53 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:668
2024-08-24 01:24:53 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:668
2024-08-24 01:24:53 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:668
2024-08-24 01:24:54 INFO     epoch is incremented. current_epoch: 0, epoch: 1                          train_util.py:668
Traceback (most recent call last):
  File "E:\TRAINING\lora-scripts\sd-scripts\flux_train_network.py", line 408, in <module>
    trainer.train(args)
  File "E:\TRAINING\lora-scripts\sd-scripts\train_network.py", line 1099, in train
    noise_pred, target, timesteps, huber_c, weighting = self.get_noise_pred_and_target(
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\TRAINING\lora-scripts\sd-scripts\flux_train_network.py", line 300, in get_noise_pred_and_target
    guidance_vec.requires_grad_(True)
RuntimeError: only Tensors of floating point dtype can require gradients
steps:   0%|                                                                                  | 0/2180 [00:53<?, ?it/s]
01:25:06-098320 ERROR    Training failed / 训练失败

**Comment by Akegarasu** [comment]
fixed
