### ISSUE TITLE
Does anyone meet the same issue ? 有人遇到类似问题了么？

### ISSUE THREAD

**Issue by NBSTpeterhill** [Akegarasu/lora-scripts#494]
Traceback (most recent call last):
  File "/root/autodl-tmp/lora-scripts/./sd-scripts/flux_train_network.py", line 446, in <module>
    trainer.train(args)
  File "/root/autodl-tmp/lora-scripts/sd-scripts/train_network.py", line 258, in train
    tokenize_strategy = self.get_tokenize_strategy(args)
  File "/root/autodl-tmp/lora-scripts/./sd-scripts/flux_train_network.py", line 145, in get_tokenize_strategy
    return strategy_flux.FluxTokenizeStrategy(t5xxl_max_token_length, args.tokenizer_cache_dir)
  File "/root/autodl-tmp/lora-scripts/sd-scripts/library/strategy_flux.py", line 28, in __init__
    self.t5xxl = self._load_tokenizer(T5TokenizerFast, T5_XXL_TOKENIZER_ID, tokenizer_cache_dir=tokenizer_cache_dir)
  File "/root/autodl-tmp/lora-scripts/sd-scripts/library/strategy_base.py", line 46, in _load_tokenizer
    tokenizer = model_class.from_pretrained(model_id, subfolder=subfolder)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2255, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'google/t5-v1_1-xxl'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'google/t5-v1_1-xxl' is the correct path to a directory containing all relevant files for a T5TokenizerFast tokenizer.

**Comment by NBSTpeterhill** [comment]
change export link---solved

**Comment by sp1cae** [comment]
same error, where did you change it ?
