### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './train/aki'

### ISSUE THREAD

**Issue by xiwei777** [Akegarasu/lora-scripts#5]
$ bash train.sh
prepare tokenizer
update token length: 225
Use DreamBooth method.
prepare train images.
Traceback (most recent call last):
  File "/data/application/xiw/project/pratice/Chilloutmix/lora-scripts/./sd-scripts/train_network.py", line 548, in <module>
    train(args)
  File "/data/application/xiw/project/pratice/Chilloutmix/lora-scripts/./sd-scripts/train_network.py", line 121, in train
    train_dataset = DreamBoothDataset(args.train_batch_size, args.train_data_dir, args.reg_data_dir,
  File "/data/application/xiw/project/pratice/Chilloutmix/lora-scripts/sd-scripts/library/train_util.py", line 754, in __init__
    train_dirs = os.listdir(train_data_dir)
FileNotFoundError: [Errno 2] No such file or directory: './train/aki'
Traceback (most recent call last):
  File "/data/application/xiw/project/pratice/Chilloutmix/lora-scripts/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/data/application/xiw/project/pratice/Chilloutmix/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/data/application/xiw/project/pratice/Chilloutmix/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/data/application/xiw/project/pratice/Chilloutmix/lora-scripts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/data/application/xiw/project/pratice/Chilloutmix/lora-scripts/venv/bin/python3', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=./sd-models/model.ckpt', '--train_data_dir=./train/aki', '--output_dir=./output', '--logging_dir=./logs', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=10', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--network_dim=32', '--network_alpha=32', '--output_name=aki', '--train_batch_size=1', '--save_every_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--xformers', '--shuffle_caption', '--use_8bit_adam']' returned non-zero exit status 1.

**Comment by Akegarasu** [comment]
需要你自己改目录
