### ISSUE TITLE
用lora-scripts启动训练报错

### ISSUE THREAD

**Issue by abbydad** [Akegarasu/lora-scripts#516]
训练配置生成的参数：
```
model_train_type = "sd-lora"
pretrained_model_name_or_path = "D:/sd-webui-aki/models/Stable-diffusion/revAnimated_v122EOL.safetensors"
v2 = false
train_data_dir = "D:/work/training/LoRA/jjyy_2.5/image"
prior_loss_weight = 1
resolution = "1024,1024"
enable_bucket = false
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64
output_name = "v2.5"
output_dir = "D:/work/training/LoRA/jjyy_2.5/models"
save_model_as = "safetensors"
save_precision = "bf16"
save_every_n_epochs = 1
max_train_epochs = 5
train_batch_size = 4
gradient_checkpointing = true
network_train_unet_only = false
network_train_text_encoder_only = false
learning_rate = 1
unet_lr = 1
text_encoder_lr = 0.00001
lr_scheduler = "cosine"
lr_warmup_steps = 0
optimizer_type = "Prodigy"
network_module = "networks.lora"
network_dim = 128
network_alpha = 64
sample_prompts = "(masterpiece, best quality:1.2) --n low quality,worst quality,bad anatomy,bad composition,poor,low effort --w 768 --h 768 --d 1 --l 7 --s 25"
sample_sampler = "euler_a"
sample_every_n_epochs = 1
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 1
max_token_length = 255
seed = 1337
clip_skip = 2
mixed_precision = "bf16"
xformers = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
persistent_data_loader_workers = true
lr_scheduler_num_cycles = 3
optimizer_args = [
  "decouple=True",
  "weight_decay=0.01",
  "use_bias_correction=True",
  "d_coef=2.0"
]
```

第一次 text_encoder_lr设置为1时报错

```
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "D:\work\lora-scripts\scripts\train_network.py", line 1445, in <module>
    trainer.train(args)
  File "D:\work\lora-scripts\scripts\train_network.py", line 478, in train
    text_encoder_lr = None if len(args.text_encoder_lr) == 0 else args.text_encoder_lr[0]
TypeError: object of type 'int' has no len()
```

第二次 修改text_encoder_lr（但不对，其实是要保持为1的？） 又报错：

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Program Files\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\work\lora-scripts\scripts\train_network.py", line 15, in <module>
    import torch
  File "D:\work\lora-scripts\venv\lib\site-packages\torch\__init__.py", line 137, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "D:\work\lora-scripts\venv\lib\site-packages\torch\lib\cufft64_11.dll" or one of its dependencies.
```

启动训练签名的日志看着正常：

```sh
19:55:46-731546 INFO     Starting SD-Trainer Mikazuki GUI...
19:55:46-733546 INFO     Base directory: D:\work\lora-scripts, Working directory: D:\work\lora-scripts
19:55:46-744545 INFO     Windows Python 3.10.9 D:\work\lora-scripts\venv\Scripts\python.exe
19:55:46-745546 INFO     detected locale zh_CN, use pip & huggingface mirrors
19:55:47-588517 INFO     Starting tageditor...
19:55:47-596517 INFO     Starting tensorboard...
19:55:47-621517 INFO     Server started at http://127.0.0.1:28000
TensorFlow installation not found - running with reduced feature set.
19:55:48-180477 INFO     Loading config from D:\work\lora-scripts\assets\config.json
19:55:48-184479 INFO     Torch 2.4.1+cu124
19:55:48-208477 INFO     Torch backend: nVidia CUDA 12.4 cuDNN 90100
19:55:48-210478 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
TensorBoard 2.10.1 at http://127.0.0.1:6006/ (Press CTRL+C to quit)
```

**Comment by Akegarasu** [comment]
更新到最新。
