### ISSUE TITLE
resume，已有的lora上继续训练，点击文件调用不了文件夹，这个只能手动填写目录吗？

### ISSUE THREAD

**Issue by wzgrx** [Akegarasu/lora-scripts#522]
记得之前版本可以调用来着

**Comment by wzgrx** [comment]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "F:\Soft\lora-scripts\mikazuki\app\application.py", line 73, in add_cache_control_header
    response = await call_next(request)
  File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "F:\Soft\lora-scripts\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\Soft\lora-scripts\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "F:\Soft\lora-scripts\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "F:\Soft\lora-scripts\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "F:\Soft\lora-scripts\mikazuki\app\api.py", line 167, in pick_file
    result = await coro
UnboundLocalError: local variable 'coro' referenced before assignment

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "F:\Soft\lora-scripts\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "F:\Soft\lora-scripts\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |   File "F:\Soft\lora-scripts\venv\lib\site-packages\fastapi\applications.py", line 276, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 106, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "F:\Soft\lora-scripts\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 685, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    |     message = await recv_stream.receive()
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\anyio\streams\memory.py", line 111, in receive
    |     return self.receive_nowait()
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\anyio\streams\memory.py", line 104, in receive_nowait
    |     raise EndOfStream
    | anyio.EndOfStream
    |
    | During handling of the above exception, another exception occurred:
    |
    | Traceback (most recent call last):
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "F:\Soft\lora-scripts\mikazuki\app\application.py", line 73, in add_cache_control_header
    |     response = await call_next(request)
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    |     raise app_exc
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    |     raise exc
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    |     await self.app(scope, receive, sender)
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    |     raise e
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    |     await self.app(scope, receive, send)
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    |     await route.handle(scope, receive, send)
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    |     await self.app(scope, receive, send)
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\starlette\routing.py", line 66, in app
    |     response = await func(request)
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    |     raw_response = await run_endpoint_function(
    |   File "F:\Soft\lora-scripts\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    |     return await dependant.call(**values)
    |   File "F:\Soft\lora-scripts\mikazuki\app\api.py", line 167, in pick_file
    |     result = await coro
    | UnboundLocalError: local variable 'coro' referenced before assignment

**Comment by wzgrx** [comment]
PermissionError: [Errno 13] Permission denied: 'F:/Soft/all/wzgrx'

**Comment by wzgrx** [comment]
这个错误是由 `UnboundLocalError` 引起的，表明在 `pick_file` 函数中变量 `coro` 在赋值前被引用了。这意味着代码尝试执行一个尚未定义的异步任务（`coro`）或异步调用。

### 解决方法：
你需要检查并确保 `coro` 在 `pick_file` 函数中被正确初始化，并且在任何地方使用它之前已经分配了一个值。

#### 可能的修复步骤：
1. **检查 `coro` 的初始化**：
   确保 `coro` 在被调用之前有适当的赋值。例如：
   ```python
   coro = some_async_function()
   ```

2. **条件语句问题**：
   如果 `coro` 是在条件语句中初始化的，确保在所有可能的分支中都赋值给 `coro`，这样可以避免某些条件下未赋值的情况。

   例如：
   ```python
   if some_condition:
       coro = some_async_function()
   else:
       coro = another_async_function()
   ```

3. **默认赋值**：
   如果 `coro` 可能在某些情况下未被赋值，可以考虑给它一个默认值。
   ```python
   coro = None
   if some_condition:
       coro = some_async_function()
   ```

4. **debugging**：
   在 `pick_file` 函数中增加一些打印语句或断点，确保 `coro` 被赋值正确：
   ```python
   print(coro)  # 检查是否为 None 或是否存在其他问题
   ```

#### 错误出现位置：
- 错误指向了 `mikazuki/app/api.py` 文件的第 167 行 `result = await coro`，这表明你在 `await` 某个未初始化的协程对象。检查第 167 行附近的代码，确保 `coro` 在执行前有正确的赋值。

### 总结：
- 找到 `coro` 在函数中的定义位置，并确保它在所有分支下都有有效的赋值。如果它依赖于某个条件，确保这个条件下总是会初始化该变量。

如果你能分享更多的代码片段，我可以提供更具体的帮助！
