### ISSUE TITLE
！！！Torch 无法使用 GPU，您无法正常开始训练！！！                          您的显卡可能并不支持，或是 torch 安装有误。请检查您的 torch 安装。

### ISSUE THREAD

**Issue by qingdengke88** [Akegarasu/lora-scripts#526]
07:31:16-523574 INFO     Starting SD-Trainer Mikazuki GUI...
07:31:16-526589 INFO     Base directory: F:\lora-scripts-main\lora-scripts-main, Working directory:
                         F:\lora-scripts-main\lora-scripts-main
07:31:16-535581 INFO     Windows Python 3.10.8 C:\Users\Xu\AppData\Local\Programs\Python\Python310\python.exe
07:31:16-536581 INFO     detected locale zh_CN, use pip & huggingface mirrors
07:31:16-537582 INFO     submodule not found, try clone...
07:31:16-538582 INFO     checking git installation...
Submodule path '../../frontend': checked out '62b5805b451c8a7d3c6841e59745b1fd76036a76'
Submodule path '../../sd-scripts': checked out '16e5981d3153ba02c34445089b998c5002a60abc'
07:31:19-430431 INFO     Starting tageditor...
07:31:19-432431 INFO     Starting tensorboard...
C:\Users\Xu\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'F:\\lora-scripts-main\\lora-scripts-main\\mikazuki\\dataset-tag-editor\\scripts\\launch.py': [Errno 2] No such file or directory
07:31:19-458938 INFO     Server started at http://127.0.0.1:28000
Traceback (most recent call last):
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\default.py", line 33, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\plugins\audio\audio_plugin.py", line 25, in <module>
    from tensorboard.data import provider
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\data\__init__.py", line 17, in <module>
    from tensorboard.data import experimental  # noqa: F401
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\data\experimental\__init__.py", line 17, in <module>
    from tensorboard.data.experimental.experiment_from_dev import (  # noqa: F401
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\data\experimental\experiment_from_dev.py", line 27, in <module>
    from tensorboard.uploader import server_info as server_info_lib
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\uploader\server_info.py", line 23, in <module>
    from tensorboard.plugins.scalar import metadata as scalars_metadata
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\plugins\scalar\metadata.py", line 18, in <module>
    from tensorboard.compat.proto import summary_pb2
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\compat\proto\summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\compat\proto\tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\compat\proto\resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\compat\proto\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\Xu\AppData\Local\Programs\Python\Python310\lib\site-packages\google\protobuf\descriptor.py", line 553, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
07:31:20-135860 INFO     Loading config from F:\lora-scripts-main\lora-scripts-main\assets\config.json
07:31:20-137859 INFO     Torch 2.2.1+cpu
07:31:20-138859 ERROR    Torch is not able to use GPU, please check your torch installation.
                          Use --skip-prepare-environment to disable this check
07:31:20-139859 ERROR    ！！！Torch 无法使用 GPU，您无法正常开始训练！！！
                         您的显卡可能并不支持，或是 torch 安装有误。请检查您的 torch 安装。

！！！Torch 无法使用 GPU，您无法正常开始训练！！！
                         您的显卡可能并不支持，或是 torch 安装有误。请检查您的 torch 安装。

请问这个报错如何解决？

**Comment by Akegarasu** [comment]
reinstall

**Comment by qingdengke88** [comment]
是自检的版本会有冲突导致的，关闭自检已经解决问题，谢谢大佬

**Comment by lidisi8520** [comment]
> 是自检的版本会有冲突导致的，关闭自检已经解决问题，谢谢大佬

怎么解决的？我也遇到了这个问题
