### ISSUE TITLE
win系统双GPU报错  use_libuv was requested but PyTorch was build without libuv support

### ISSUE THREAD

**Issue by LifeRainSunshine** [Akegarasu/lora-scripts#527]
![58F2F23BDEFBDCBD30D3A9280C78E9AA](https://github.com/user-attachments/assets/b0396dec-b128-415b-b16d-53da8c44b6a8)
又会修改的吗

**Comment by LifeRainSunshine** [comment]
补充报错内容
16:15:30-494099 INFO     Loading config from D:\E-AIGD\lora-scripts\assets\config.json
16:15:30-503117 INFO     Torch 2.4.1+cu124
16:15:30-560752 INFO     Torch backend: nVidia CUDA 12.4 cuDNN 90100
16:15:30-569774 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 23028 Arch (8, 9) Cores 128
16:15:30-572773 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 23028 Arch (8, 9) Cores 128
TensorBoard 2.10.1 at http://127.0.0.1:6006/ (Press CTRL+C to quit)
16:15:52-188385 INFO     Training started with config file / 训练开始，使用配置文件:
                         D:\E-AIGD\lora-scripts\config\autosave\20240925-161552.toml
16:15:52-191386 INFO     Using GPU(s) / 使用 GPU: ['0', '1']
16:15:52-194400 INFO     Task bce172ef-ad97-4058-849d-d8d0b9b528c3 created
W0925 16:15:55.088000 23384 torch\distributed\elastic\multiprocessing\redirects.py:28] NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "C:\Users\admin\.pyenv\pyenv-win\versions\3.10.11\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\.pyenv\pyenv-win\versions\3.10.11\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1116, in <module>
    main()
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1112, in main
    launch_command(args)
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1097, in launch_command
    multi_gpu_launcher(args)
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 734, in multi_gpu_launcher
    distrib_run.run(args)
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\torch\distributed\run.py", line 892, in run
    elastic_launch(
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\torch\distributed\launcher\api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\torch\distributed\launcher\api.py", line 255, in launch_agent
    result = agent.run()
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 680, in run
    result = self._invoke_run(role)
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 829, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 652, in _initialize_workers
    self._rendezvous(worker_group)
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 489, in _rendezvous
    rdzv_info = spec.rdzv_handler.next_rendezvous()
  File "D:\E-AIGD\lora-scripts\venv\lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 66, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: use_libuv was requested but PyTorch was build without libuv support
16:15:57-847419 ERROR    Training failed / 训练失败

**Comment by LifeRainSunshine** [comment]
- 还是报同样的错误。。。

**Comment by cooffer** [comment]
> * 还是报同样的错误。。。

这个问题解决了吗？我也遇到这个问题了，使用单卡可以跑，多卡就报 use_libuv 的错误

**Comment by lidisi8520** [comment]
> > * 还是报同样的错误。。。
> 
> 这个问题解决了吗？我也遇到这个问题了，使用单卡可以跑，多卡就报 use_libuv 的错误

你好，解决了吗？我的也是一样的报错
