### ISSUE TITLE
双GPU训练SDXL报错RuntimeError: use_libuv was requested but PyTorch was build without libuv support

### ISSUE THREAD

**Issue by newhuman011** [Akegarasu/lora-scripts#538]
已经看过87826ea内容，确认过[mikazuki/process.py]确实有其中几行，仍然报这个错误。训练FLUX倒是没问题。

报错内容：
15:07:04-826324 INFO     Starting SD-Trainer Mikazuki GUI...
15:07:04-830320 INFO     Base directory: E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5, Working directory:
                         E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5
15:07:04-831322 INFO     Windows Python 3.10.11 E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\python.exe
15:07:04-832320 INFO     detected locale zh_CN, use pip & huggingface mirrors
15:07:07-279103 INFO     SD-Trainer Version: v1.10.0
15:07:07-281102 INFO     Starting tageditor...
15:07:07-283101 INFO     Starting tensorboard...
15:07:07-319144 INFO     Server started at http://127.0.0.1:28000
15:07:08-372955 INFO     Loading config from E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\assets\config.json
15:07:08-376957 INFO     Torch 2.4.1+cu124
15:07:08-441011 INFO     Torch backend: nVidia CUDA 12.4 cuDNN 90100
15:07:08-446009 INFO     Torch detected GPU: NVIDIA GeForce RTX 3070 VRAM 16384 Arch (8, 6) Cores 46
TensorBoard 2.10.1 at http://127.0.0.1:6006/ (Press CTRL+C to quit)
15:07:28-546543 INFO     Wrote promopts to file
                         E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\config\autosave\20241005-150728-promopt.txt
15:07:28-548542 INFO     Training started with config file / 训练开始，使用配置文件:
                         E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\config\autosave\20241005-150728.toml
15:07:28-549541 INFO     Using GPU(s) / 使用 GPU: ['0', '1']
15:07:28-550543 INFO     Task bb9b4cf5-1066-4964-8735-a22cae0ff766 created
W1005 15:07:30.096000 15120 torch\distributed\elastic\multiprocessing\redirects.py:28] NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\accelerate\commands\launch.py", line 1116, in <module>
    main()
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\accelerate\commands\launch.py", line 1112, in main
    launch_command(args)
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\accelerate\commands\launch.py", line 1097, in launch_command
    multi_gpu_launcher(args)
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\accelerate\commands\launch.py", line 734, in multi_gpu_launcher
    distrib_run.run(args)
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\torch\distributed\run.py", line 892, in run
    elastic_launch(
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\torch\distributed\launcher\api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\torch\distributed\launcher\api.py", line 255, in launch_agent
    result = agent.run()
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 680, in run
    result = self._invoke_run(role)
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 829, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 652, in _initialize_workers
    self._rendezvous(worker_group)
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 489, in _rendezvous
    rdzv_info = spec.rdzv_handler.next_rendezvous()
  File "E:\lora-scripts-v1.8.5\lora-scripts-v1.8.5\python\lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 66, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: use_libuv was requested but PyTorch was build without libuv support
15:07:32-531947 ERROR    Training failed / 训练失败

**Comment by lidisi8520** [comment]
你好，解决了吗？我不仅在使用多gpu的时候报这个错，我在训练flux的时候，也是报这个错。
