### ISSUE TITLE
Flux无法续炼

### ISSUE THREAD

**Issue by 2575044704** [Akegarasu/lora-scripts#547]
报错提示没有文件夹，但是我的文件夹是存在的，并且里面也不是空的
```
2024-10-12 20:56:32 INFO     resume training from local state: /root/output2/work_v4-000004.safetensors                                     train_util.py:4279
Traceback (most recent call last):
  File "/root/lora-scripts/./scripts/dev/flux_train_network.py", line 519, in <module>
    trainer.train(args)
  File "/root/lora-scripts/scripts/dev/train_network.py", line 695, in train
    train_util.resume_from_local_or_hf_if_specified(accelerator, args)
  File "/root/lora-scripts/scripts/dev/library/train_util.py", line 4280, in resume_from_local_or_hf_if_specified
    accelerator.load_state(args.resume)
  File "/root/lora-scripts/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 3072, in load_state
    raise ValueError(f"Tried to find {input_dir} but folder does not exist")
ValueError: Tried to find /root/output2/work_v4-000004.safetensors but folder does not exist

```
![image](https://github.com/user-attachments/assets/e65935ae-9a65-40cc-91b4-6813e0aad410)

**Comment by 2575044704** [comment]
解决了，是文件夹路径不是文件路径。按照下面填就可以了。说明有误，望更新后改正一下
![image](https://github.com/user-attachments/assets/14cfa097-9729-44c6-84bc-cc2ce9388c74)
