### ISSUE TITLE
训练时出现的错误

### ISSUE THREAD

**Issue by yuanch1** [Akegarasu/lora-scripts#60]
```
[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 76/76 [00:00<00:00, 4675.58it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 640), count: 54
bucket 1: resolution (448, 576), count: 12
bucket 2: resolution (512, 512), count: 342
bucket 3: resolution (640, 384), count: 48
mean ar error (without repeats): 0.022491709236204763
prepare accelerator
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint
C:\Users\default.DESKTOP-08UGQK7\Desktop\lora-scripts-main\venv\lib\site-packages\safetensors\torch.py:98: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
C:\Users\default.DESKTOP-08UGQK7\Desktop\lora-scripts-main\venv\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
C:\Users\default.DESKTOP-08UGQK7\Desktop\lora-scripts-main\venv\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Traceback (most recent call last):
  File "C:\Users\default.DESKTOP-08UGQK7\Desktop\lora-scripts-main\sd-scripts\train_network.py", line 724, in <module>
    train(args)
  File "C:\Users\default.DESKTOP-08UGQK7\Desktop\lora-scripts-main\sd-scripts\train_network.py", line 135, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(
  File "C:\Users\default.DESKTOP-08UGQK7\Desktop\lora-scripts-main\sd-scripts\library\train_util.py", line 2649, in load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, name_or_path, device)
  File "C:\Users\default.DESKTOP-08UGQK7\Desktop\lora-scripts-main\sd-scripts\library\model_util.py", line 869, in load_models_from_stable_diffusion_checkpoint
    _, state_dict = load_checkpoint_with_text_encoder_conversion(ckpt_path, device)
  File "C:\Users\default.DESKTOP-08UGQK7\Desktop\lora-scripts-main\sd-scripts\library\model_util.py", line 844, in load_checkpoint_with_text_encoder_conversion
    state_dict = load_file(ckpt_path) # , device) # may causes error
  File "C:\Users\default.DESKTOP-08UGQK7\Desktop\lora-scripts-main\venv\lib\site-packages\safetensors\torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: shape '[1280, 1280, 3, 3]' is invalid for input of size 3657939
Traceback (most recent call last):
  File "C:\Users\default.DESKTOP-08UGQK7\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\default.DESKTOP-08UGQK7\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\default.DESKTOP-08UGQK7\Desktop\lora-scripts-main\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\default.DESKTOP-08UGQK7\Desktop\lora-scripts-main\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\default.DESKTOP-08UGQK7\Desktop\lora-scripts-main\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\default.DESKTOP-08UGQK7\Desktop\lora-scripts-main\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\default.DESKTOP-08UGQK7\\Desktop\\lora-scripts-main\\venv\\Scripts\\python.exe', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=./sd-models/v1-5-pruned-emaonly.safetensors', '--train_data_dir=./train/nine-age', '--output_dir=./output', '--logging_dir=./logs', '--log_prefix=nine_ling', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=10', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=nine_ling', '--train_batch_size=1', '--save_every_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--keep_tokens=0']' returned non-zero exit status 1.
Train finished
```

以上是运行train.ps1时出现的报错，基础模型也换了，文件名照着大佬发的视频又检查了一遍还是不行，人已经傻了

**Comment by yuanch1** [comment]
![image](https://user-images.githubusercontent.com/52809871/229364849-f3fa8902-d4b3-4afa-abf1-cb7cc52e8ccf.png)
另外发现在运行install时无论如何xformers都会再安装一遍

**Comment by Georgebillion** [comment]
确认素材分辨率，这玩意有点像你分辨率设置错误了

**Comment by 4nth0ny1130** [comment]
Check the base model hash, this error looks like a problem with your v1-5-pruned-emaonly.safetensors model

**Comment by yuanch1** [comment]
thanks，i reinstall the script，it can work，i think maybe is network reason

谢谢佬们，重新下载了一遍就能用了，前面连下几遍都没有成功，不过现在能用了，另外好像不是分辨率的问题，因为我是用的同一个文件夹作为训练对象

在 2023年4月10日星期一，4nth0ny1130 ***@***.***> 写道：

**Comment by beetaa** [comment]
你的底模如果是2.0/2.1版本，需要修改 `is_v2_model = 1`
