### ISSUE TITLE
UnboundLocalError: local variable 'prompts' referenced before assignment

### ISSUE THREAD

**Issue by Charlo-O** [Akegarasu/lora-scripts#603]
Traceback (most recent call last):
  File "/root/lora-scripts/./scripts/dev/flux_train_network.py", line 574, in <module>
    trainer.train(args)
  File "/root/lora-scripts/scripts/dev/train_network.py", line 436, in train
    self.cache_text_encoder_outputs_if_needed(args, accelerator, unet, vae, text_encoders, train_dataset_group, weight_dtype)
  File "/root/lora-scripts/./scripts/dev/flux_train_network.py", line 223, in cache_text_encoder_outputs_if_needed
    prompts = train_util.load_prompts(args.sample_prompts)
  File "/root/lora-scripts/scripts/dev/library/train_util.py", line 6066, in load_prompts
    for i in range(len(prompts)):
UnboundLocalError: local variable 'prompts' referenced before assignment
02:12:16-306768 ERROR    Training failed / 训�失败                      

if not getattr(torch, "has_mps", False):
02:10:10-699897 INFO     Torch backend: nVidia CUDA 12.4 cuDNN 90100
02:10:10-741032 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 D VRAM
                         24210 Arch (8, 9) Cores 114
/root/lora-scripts/venv/lib/python3.10/site-packages/gradio/components/dropdarning: The value passed into gr.Dropdown() is not in the list of choices. P=Tst of choices to include:  or set allow_custom_value=True.
warnings.warn(

**Comment by Charlo-O** [comment]
我两个服务器都遇到这个问题了，，
