### ISSUE TITLE
returned non-zero exit status 1.

### ISSUE THREAD

**Issue by ANGJustinl** [Akegarasu/lora-scripts#63]
# 为避免无效问题和冗余问题，提问前请确认

- [X] 你确定Google不能解决你的问题
- [x] 你确定已有的issue不能解决你的问题
- [X] 你确定类似的issue不能解决你的问题

# Describe the bug 描述你遇到的问题

- 无法启动训练

```running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 1216
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 608
  num epochs / epoch数: 12
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 7296
steps:   0%|                                                                                  | 0/7296 [00:00<?, ?it/s]epoch 1/12
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\Stable_diffusion\lora训练\lora-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\Stable_diffusion\lora训练\lora-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "F:\Stable_diffusion\lora训练\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "F:\Stable_diffusion\lora训练\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\Stable_diffusion\\lora训练\\lora-scripts\\venv\\Scripts\\python.exe', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=./sd-models/grapefruitHentaiModel_grapefruitv4.safetensors', '--train_data_dir=./train/riru', '--output_dir=./output', '--logging_dir=./logs', '--log_prefix=riru', '--resolution=512,640', '--network_module=networks.lora', '--max_train_epochs=12', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=riru', '--train_batch_size=1', '--save_every_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--use_8bit_adam']' returned non-zero exit status 1.
Train finished
True
```
# To Reproduce 如何重现问题

1. 完成了 install-cn.ps1
2. pull 了最新仓库
3. 检查了venv
4. 根据issue 重新下载了huggingface\hub\models--openai--clip-vit-large-patch14 
5. 使用 Tesla P40

# System
- OS: win10
- Python Version : follow venv
- Package Version : follow venv

**Comment by ANGJustinl** [comment]
Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu 
这个报错我不是很能解决(from google),会对训练有很大影响吗

**Comment by ANGJustinl** [comment]
我也尝试使用代理但并未改变问题

**Comment by ANGJustinl** [comment]
复现4的issue #12

**Comment by ANGJustinl** [comment]
解决方法 关闭use_8bit_adam 
```
$use_8bit_adam = 0 # use 8bit adam optimizer | 使用 8bit adam 优化器节省显存，默认启用。部分 10 系老显卡无法使用，修改为 0 禁用。
```

**Comment by Georgebillion** [comment]
P40 不至于 8bit Adam 不可用 这个问题我记得是bnb没装上的问题 建议检查一下安装依赖的时候有无报错

**Comment by ANGJustinl** [comment]
安装依赖是有报错的
安装其他依赖的时候超时

然后我是自己跟着 `install_cn.ps1`这个文件自己在虚拟环境里安装的

**Comment by littlestone0806** [comment]
> P40 不至于 8bit Adam 不可用 这个问题我记得是bnb没装上的问题 建议检查一下安装依赖的时候有无报错

你好，目前我也是遇到这个问题，可以说一下bnb的全称么，我去试试

**Comment by ANGJustinl** [comment]
https://github.com/TimDettmers/bitsandbytes

**Comment by Georgebillion** [comment]
> 安装依赖是有报错的 安装其他依赖的时候超时
> 
> 然后我是自己跟着 `install_cn.ps1`这个文件自己在虚拟环境里安装的

如果超时建议开一下代理看看

**Comment by Georgebillion** [comment]
还有我记得P40发布的时候是16系还是20系显卡的时候了？不存在bnb装不上吧？

**Comment by Akegarasu** [comment]
p40我记得就是用不了8bit adam

**Comment by littlestone0806** [comment]
bnb能装上是没问题，就是p40，m40之类的，还是会报错。试了一下别人用1080ti编译的bnb的dll，0.37.0和0.35.0都跑不起来，放弃了

**Comment by aqraycn** [comment]
换model，换优化器~~

**Comment by ANGJustinl** [comment]
无所谓我在用lion

**Comment by BasicSix** [comment]
我这边也出现了相关报错,多方探索\苦求代码\一无所获.
最后,我把底模换了,问题解决了,世界清净了.
