### ISSUE TITLE
Returned non-zero exit status 1 after starting the training script

### ISSUE THREAD

**Issue by SkilledExtractor** [Akegarasu/lora-scripts#80]
After starting the training script, the training does not start properly and the following error codes are reported :
Traceback (most recent call last):
  File "E:\Program Files\AI\lora-scripts\sd-scripts\train_network.py", line 14, in <module>
    from diffusers import DDPMScheduler
  File "e:\program files\ai\lora-scripts\venv\lib\site-packages\diffusers\__init__.py", line 27, in <module>
    from .modeling_utils import ModelMixin
  File "e:\program files\ai\lora-scripts\venv\lib\site-packages\diffusers\modeling_utils.py", line 58, in <module>
    import safetensors
  File "e:\program files\ai\lora-scripts\venv\lib\site-packages\safetensors\__init__.py", line 4, in <module>
    from .safetensors_rust import safe_open  # noqa: F401
ModuleNotFoundError: No module named 'safetensors.safetensors_rust'
Traceback (most recent call last):
  File "D:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Program Files\AI\lora-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "e:\program files\ai\lora-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "e:\program files\ai\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "e:\program files\ai\lora-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['e:\\program files\\ai\\lora-scripts\\venv\\scripts\\python.exe', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=./sd-models/chilloutmix_NiPrunedFp32Fix.safetensors', '--train_data_dir=./train/lyw', '--output_dir=./output', '--logging_dir=./logs', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=20', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=lyw', '--train_batch_size=1', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--clip_skip=2', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--xformers', '--shuffle_caption', '--use_lion_optimizer']' returned non-zero exit status 1.
Train finished
正常安装后无法启动训练，运行训练脚本出现上列报错，现有issues无法解决我的问题。
设备环境：Windows 10 22H2 With CODA GPU

**Comment by muximuxi** [comment]
请问这个问题解决了吗？怎么解决的呀？

**Comment by liuchangzong** [comment]
我也有这个错误，吐了

**Comment by liuchangzong** [comment]
ModuleNotFoundError: No module named 'safetensors.safetensors_rust'
你看下报错里面，有上面这行代码，
pip install XX看看行不行
