### ISSUE TITLE
No Data Found

### ISSUE THREAD

**Issue by liuyi0501** [Akegarasu/lora-scripts#87]
我把素材放到./raw
我设置 train_data_dir = ./raw 后运行
bash train.sh
prepare tokenizer
update token length: 225
Use DreamBooth method.
prepare train images.
0 train images with repeating.
loading image sizes.
0it [00:00, ?it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
/home/zyt/.local/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/zyt/.local/lib/python3.10/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
mean ar error (without repeats): nan
No data found. Please verify arguments (train_data_dir must be the parent of folders with images) / 画像がありません。引数指定を確認してください（train_data_dirには画像があるフォルダではなく、画像があるフォルダの親フォルダを指定する必要があります）

但如果设置为我设置 train_data_dir = ../raw
就报错
bash train.sh                                                                           prepare tokenizer
update token length: 225
Use DreamBooth method.
prepare train images.
Traceback (most recent call last):
  File "/home/zyt/lora-scripts/./sd-scripts/train_network.py", line 507, in <module>
    train(args)
  File "/home/zyt/lora-scripts/./sd-scripts/train_network.py", line 61, in train
    train_dataset = DreamBoothDataset(args.train_batch_size, args.train_data_dir, args.reg_data_dir,                                                                                  File "/home/zyt/lora-scripts/sd-scripts/library/train_util.py", line 760, in __init__
    train_dirs = os.listdir(train_data_dir)
FileNotFoundError: [Errno 2] No such file or directory: '../raw'
Traceback (most recent call last):
  File "/home/zyt/anaconda3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/zyt/anaconda3/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main                                                                       args.func(args)
  File "/home/zyt/anaconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 923, in launch_command                                                                    simple_launcher(args)
  File "/home/zyt/anaconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 579, in simple_launcher                                                                   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zyt/anaconda3/bin/python', './sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=./sd-models/model.ckpt', '--train_data_dir=../raw', '--output_dir=./output', '--logging_dir=./logs', '--log_prefix=bdap', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=10', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=bdap', '--train_batch_size=1', '--save_every_n_epochs=2', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1337', '--cache_latents', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--clip_skip', '2', '--optimizer_type', 'AdamW8bit']' returned non-zero exit status 1.

train.sh内容如下：
#!/bin/bash                                                                               # LoRA train script by @Akegarasu                                                         
# Train data path | 设置训练用模型、图片                                                  pretrained_model="./sd-models/model.ckpt" # base model path | 底模路径                    is_v2_model=0                             # SD2.0 model | SD2.0模型 2.0模型下 clip_skip 默认无效
parameterization=0                        # parameterization | 参数化 本参数需要和 V2 参数同步使用 实验性功能                                                                       train_data_dir="./raw"              # train dataset path | 训练数据集路径
reg_data_dir=""                           # directory for regularization images | 正则化数
据集路径，默认不使用正则化图像。                                                          # Network settings | 网络设置                                                             network_module="networks.lora" # 在这里将会设置训练的网络种类，默认为 networks.lora 也就是 LoRA 训练。如果你想训练 LyCORIS（LoCon、LoHa） 等，则修改这个值为 lycoris.kohya
network_weights=""             # pretrained weights for LoRA network | 若需要从已有的 LoRA 模型上继续训练，请填写 LoRA 模型路径。                                                   network_dim=32                 # network dim | 常用 4~128，不是越大越好                   network_alpha=32               # network alpha | 常用与 network_dim 相同的值或者采用较小的值，如 network_dim的一半 防止下溢。默认值为 1，使用较小的 alpha 需要提升学习率。          # Train related params | 训练相关参数                                                     resolution="512,512"  # image resolution w,h. 图片分辨率，宽,高。支持非正方形，但必须是 64 倍数。                                                                                   batch_size=1          # batch size                                                        max_train_epoches=10  # max train epoches | 最大训练 epoch
save_every_n_epochs=2 # save every n epochs | 每 N 个 epoch 保存一次                      train_unet_only=0         # train U-Net only | 仅训练 U-Net，开启这个会牺牲效果大幅减少显>存使用。6G显存可以开启                                                                    train_text_encoder_only=0 # train Text Encoder only | 仅训练 文本编码器                   stop_text_encoder_training=0 # stop text encoder training | 在第N步时停止训练文本编码器   noise_offset="0"  # noise offset | 在训练中添加噪声偏移来改良生成非常暗或者非常亮的图像，>如果启用，推荐参数为0.1                                                                   keep_tokens=0   # keep heading N tokens when shuffling caption tokens | 在随机打乱 tokens 时，保留前 N 个不变。
min_snr_gamma=0 # minimum signal-to-noise ratio (SNR) value for gamma-ray | 伽马射线事件的最小信噪比（SNR）值  默认为 0
# Learning rate | 学习率                                                                  lr="1e-4"                                                                                 unet_lr="1e-4"                                                                            text_encoder_lr="1e-5"
lr_scheduler="cosine_with_restarts" # "linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup", "adafactor"                                     lr_warmup_steps=0                   # warmup steps | 学习率预热步数，lr_scheduler 为 constant 或 adafactor 时该值需要设为0。                                                        lr_restart_cycles=1                 # cosine_with_restarts restart cycles | 余弦退火重启次
数，仅在 lr_scheduler 为 cosine_with_restarts 时起效。                                    # Output settings | 输出设置
output_name="bdap"           # output model name | 模型保存名称                           save_model_as="safetensors" # model save ext | 模型保存格式 ckpt, pt, safetensors         # Resume training state | 恢复训练设置                                                    save_state=0 # save state | 保存训练状态 名称类似于 <output_name>-??????-state ?????? 表示 epoch 数                                                                                 resume=""    # resume from state | 从某个状态文件夹中恢复训练 需配合上方参数同时使用 由于>规范文件限制 epoch 数和全局步数不会保存 即使恢复时它们也从 1 开始 与 network_weights 的具>体实现操作并不一致                                                                        # 其他设置                                                                                min_bucket_reso=256              # arb min resolution | arb 最小分辨率                    max_bucket_reso=1024             # arb max resolution | arb 最大分辨率                    persistent_data_loader_workers=0 # persistent dataloader workers | 容易爆内存，保留加载训>练集的worker，减少每个 epoch 之间的停顿                                                   clip_skip=2                      # clip skip | 玄学 一般用 2                              # 优化器设置                                                                              optimizer_type="AdamW8bit" # Optimizer type | 优化器类型 默认为 8bitadam，可选：AdamW AdamW8bit Lion SGDNesterov SGDNesterov8bit DAdaptation AdaFactor                              # LyCORIS 训练设置                                                                        algo="lora"  # LyCORIS network algo | LyCORIS 网络算法 可选 lora、loha、lokr、ia3、dylora>。lora即为locon

**Comment by liuyi0501** [comment]
我找到解决办法了
需要在/raw文件夹下创建个 <数字>_<字符>的文件夹，然后把图片放进去
https://github.com/kohya-ss/sd-scripts/issues/78
